386_OBJECTS= \
    $(_OBJ_DIR)\i386\certreq.res \
    $(_OBJ_DIR)\i386\certreq.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\certreq.res \
    $(_OBJ_DIR)\ia64\certreq.obj

PASS0_IA64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\certreq.res \
    $(_OBJ_DIR)\amd64\certreq.obj

PASS0_AMD64_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\certreq.res \
    $(_OBJ_DIR)\arm\certreq.obj

PASS0_ARM_OBJECTS=

