386_OBJECTS= \
    $(_OBJ_DIR)\i386\perfdata.obj \
    $(_OBJ_DIR)\i386\perfdisp.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\perfdata.obj \
    $(_OBJ_DIR)\ia64\perfdisp.obj

PASS0_IA64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\perfdata.obj \
    $(_OBJ_DIR)\amd64\perfdisp.obj

PASS0_AMD64_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\perfdata.obj \
    $(_OBJ_DIR)\arm\perfdisp.obj

PASS0_ARM_OBJECTS=

