386_OBJECTS= \
    $(_OBJ_DIR)\i386\dummy.obj \
    $(_OBJ_DIR)\i386\certadml.res

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\dummy.obj \
    $(_OBJ_DIR)\ia64\certadml.res

PASS0_IA64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\dummy.obj \
    $(_OBJ_DIR)\amd64\certadml.res

PASS0_AMD64_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\dummy.obj \
    $(_OBJ_DIR)\arm\certadml.res

PASS0_ARM_OBJECTS=

