/**********************************************************************/
/**                       Microsoft Windows NT                       **/
/**                Copyright(c) Microsoft Corp., 1993                **/
/**********************************************************************/

/*
    inetamsg.h

    This file is generated by the MC tool from the INETAMSG.MC message
    file.


    FILE HISTORY:
        Johnl       16-Mar-1995 Created.
        CezaryM     11-May-2000 Added events:
                                started/stopped/paused/resumed

*/


#ifndef _INETAMSG_H_
#define _INETAMSG_H_

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: INET_SVCS_FAILED_LOGON
//
// MessageText:
//
//  The server was unable to logon the Windows NT account '%1' due to the following error: %2 The data is the error code.
//
#define INET_SVCS_FAILED_LOGON           0x80000064L

//
// MessageId: INET_SVC_ADD_VIRTUAL_ROOT_FAILED
//
// MessageText:
//
//  The server was unable to add the virtual root '%1' for the directory '%2' due to the following error: %3 The data is the error code.
//
#define INET_SVC_ADD_VIRTUAL_ROOT_FAILED 0x80000065L

//
// MessageId: INET_SVC_ODBC_DLL_LOAD_FAILED
//
// MessageText:
//
//  The server was unable to load ODBC32.DLL for sql logging due to the following error: %1 The data is the error code.
//
#define INET_SVC_ODBC_DLL_LOAD_FAILED    0xC0000066L

//
// MessageId: INET_SVC_ODBC_OPEN_FAILED
//
// MessageText:
//
//  The server was unable to open ODBC Data source %1, Table: %2, under UserName %3. The ODBC Error is: %4. The data is the error code.
//
#define INET_SVC_ODBC_OPEN_FAILED        0xC0000067L

//
// MessageId: INET_SVC_LOG_PARAMETERS_LONG
//
// MessageText:
//
//  The parameters specified for logging are too long. Field: %1; Data Given: %2.
//
#define INET_SVC_LOG_PARAMETERS_LONG     0xC0000068L

//
// MessageId: INET_SVC_SERVICE_REG_FAILED
//
// MessageText:
//
//  The server was unable to register the administration tool discovery information.  The administration tool may not be able to see this server.  The data is the error code.
//
#define INET_SVC_SERVICE_REG_FAILED      0xC0000069L

//
// MessageId: INET_SVC_LOG_CREATION_FAILED
//
// MessageText:
//
//  The Creation of InetLog Context failed. The data is the error code.
//
#define INET_SVC_LOG_CREATION_FAILED     0xC000006AL

//
// MessageId: INET_SVC_LOG_INFORMATION_FAILED
//
// MessageText:
//
//  Logging information failed. The log object was never created possibly due to wrong configuration.
//
#define INET_SVC_LOG_INFORMATION_FAILED  0xC000006BL

//
// MessageId: INET_SVC_INVALID_LOGFILE_DIRECTORY
//
// MessageText:
//
//  The server was unable to find the log file directory %1. The data is the error code.
//
#define INET_SVC_INVALID_LOGFILE_DIRECTORY 0xC000006CL

//
// MessageId: INET_SVC_LOGGING_SUSPENDED
//
// MessageText:
//
//  The server has suspended request logging because an error occured writing a log record.  The data is the error code.  The error code text is: %1.
//
#define INET_SVC_LOGGING_SUSPENDED       0xC000006DL

//
// MessageId: INET_SVC_LOGGING_RESUMED
//
// MessageText:
//
//  The server has resumed request logging.
//
#define INET_SVC_LOGGING_RESUMED         0xC000006EL

//
// MessageId: INET_SVC_WINSOCK_INIT_FAILED
//
// MessageText:
//
//  The service could not initialize the socket library.  The data is the error code.
//
#define INET_SVC_WINSOCK_INIT_FAILED     0xC000006FL

//
// MessageId: INET_SVC_GET_MODULE_FAILED
//
// MessageText:
//
//  The service could not find module %1.  The data is the error code.
//
#define INET_SVC_GET_MODULE_FAILED       0xC0000070L

//
// MessageId: INET_SVC_INVALID_BINDING
//
// MessageText:
//
//  Instance %1 has invalid binding descriptor %2.
//
#define INET_SVC_INVALID_BINDING         0x80000071L

//
// MessageId: INET_SVC_INVALID_SECURE_BINDING
//
// MessageText:
//
//  Instance %1 has invalid secure binding descriptor %2 (host name ignored).
//
#define INET_SVC_INVALID_SECURE_BINDING  0x80000072L

//
// MessageId: INET_SVC_FATAL_BINDING_ERROR
//
// MessageText:
//
//  The service could not bind instance %1.  The data is the error code.
//
#define INET_SVC_FATAL_BINDING_ERROR     0xC0000073L

//
// MessageId: INET_SVC_INVALID_MB_PATH
//
// MessageText:
//
//  The service metabase path '%1' could not be opened.  The data is the error code.
//
#define INET_SVC_INVALID_MB_PATH         0xC0000074L

//
// MessageId: INET_SVC_EVENT_SERVICE_STARTED
//
// MessageText:
//
//  %1 Service started.
//
#define INET_SVC_EVENT_SERVICE_STARTED   0x40000075L

//
// MessageId: INET_SVC_EVENT_SERVICE_STOPPED
//
// MessageText:
//
//  %1 Service stopped.
//
#define INET_SVC_EVENT_SERVICE_STOPPED   0x40000076L

//
// MessageId: INET_SVC_EVENT_SERVICE_PAUSED
//
// MessageText:
//
//  %1 Service paused.
//
#define INET_SVC_EVENT_SERVICE_PAUSED    0x40000077L

//
// MessageId: INET_SVC_EVENT_SERVICE_RESUMED
//
// MessageText:
//
//  %1 Service resumed.
//
#define INET_SVC_EVENT_SERVICE_RESUMED   0x40000078L


#endif  // _INETAMSG_H_

/**********************************************************************/
/**                       Microsoft Windows NT                       **/
/**                Copyright(c) Microsoft Corp., 1993                **/
/**********************************************************************/

/*
    w3msg.h

    This file is generated by the MC tool from the W3MSG.MC message
    file.


    FILE HISTORY:
        KeithMo     19-Mar-1993 Created.

*/


#ifndef _W3MSG_H_
#define _W3MSG_H_

//
// MessageId: W3_EVENT_CANNOT_INITIALIZE_SECURITY
//
// MessageText:
//
//  HTTP Server could not initialize its security.  The data is the error.
//
#define W3_EVENT_CANNOT_INITIALIZE_SECURITY 0xC0000899L

//
// MessageId: W3_EVENT_CANNOT_INITIALIZE_WINSOCK
//
// MessageText:
//
//  HTTP Server could not initialize the socket library.  The data is the error.
//
#define W3_EVENT_CANNOT_INITIALIZE_WINSOCK 0xC000089BL

//
// MessageId: W3_EVENT_OUT_OF_MEMORY
//
// MessageText:
//
//  HTTP Server was unable to initialize due to a shortage of available memory.  The data is the error.
//
#define W3_EVENT_OUT_OF_MEMORY           0xC000089CL

//
// MessageId: W3_EVENT_CANNOT_CREATE_CONNECTION_SOCKET
//
// MessageText:
//
//  HTTP Server could not create the main connection socket.  The data is the error.
//
#define W3_EVENT_CANNOT_CREATE_CONNECTION_SOCKET 0xC000089EL

//
// MessageId: W3_EVENT_CANNOT_CREATE_CLIENT_CONN
//
// MessageText:
//
//  HTTP Server could not create a client connection object for user at host %1.  The connection to this user is terminated.  The data is the error.
//
#define W3_EVENT_CANNOT_CREATE_CLIENT_CONN 0xC00008A0L

//
// MessageId: W3_EVENT_FILTER_DLL_LOAD_FAILED
//
// MessageText:
//
//  The HTTP Filter DLL %1 failed to load.  The data is the error.
//
#define W3_EVENT_FILTER_DLL_LOAD_FAILED  0xC00008A6L

//
// MessageId: W3_EVENT_KILLING_SCRIPT
//
// MessageText:
//
//  The script started from the URL '%1' with parameters '%2' has not responded within the configured timeout period.  The HTTP server is terminating the script.
//
#define W3_EVENT_KILLING_SCRIPT          0xC00008A8L

//
// MessageId: W3_MSG_SSI_ERROR
//
// MessageText:
//
//  The HTTP server encountered an error processing the server side include file '%1'.<BR>The error was '%2'.<BR>
//
#define W3_MSG_SSI_ERROR                 0xC00008AAL

//
// MessageId: W3_EVENT_EXTENSION_EXCEPTION
//
// MessageText:
//
//  The HTTP server encountered an unhandled exception while processing the ISAPI Application '%1'.
//
#define W3_EVENT_EXTENSION_EXCEPTION     0xC00008ABL

//
// MessageId: W3_EVENT_EXTENSION_LOAD_FAILED
//
// MessageText:
//
//  The HTTP server was unable to load the ISAPI Application '%1'. The data is the error.
//
#define W3_EVENT_EXTENSION_LOAD_FAILED   0xC00008ACL

//
// MessageId: W3_MSG_SSI_TOO_MANY_NESTED_INCLUDES
//
// MessageText:
//
//  A server side include file has included itself or the maximum depth of server side includes has been exceeded.
//
#define W3_MSG_SSI_TOO_MANY_NESTED_INCLUDES 0xC00008ADL

//
// MessageId: W3_MSG_READ_RAW_MUST_BE_GLOBAL
//
// MessageText:
//
//  An attempt was made to load filter '%1' on a server instance but it requires
//  the SF_NOTIFY_READ_RAW_DATA filter notification so it must be loaded as a global
//  filter.
//
#define W3_MSG_READ_RAW_MUST_BE_GLOBAL   0xC00008AEL

//
// MessageId: W3_MSG_LOADED_FILTER_FROM_REG
//
// MessageText:
//
//  For compatibility with previous versions of IIS, the filter '%1' was loaded as a global filter from the registry.
//  To control the filter with the Internet Service Manager, remove the filter from the
//  registry and add it as a global filter with Internet Service Manager.  Filters in the
//  registry are stored at "HKLM\System\CurrentControlSet\Services\W3Svc\Parameters\Filter DLLs".
//
#define W3_MSG_LOADED_FILTER_FROM_REG    0x400008AFL

//
// MessageId: W3_EVENT_CANNOT_READ_FILE_SECURITY
//
// MessageText:
//
//  The server was unable to read the file %1 due to a lack of access permissions.
//
#define W3_EVENT_CANNOT_READ_FILE_SECURITY 0x800008B2L

//
// MessageId: W3_EVENT_CAL_SSL_EXCEEDED
//
// MessageText:
//
//  The server was unable to acquire a license for a SSL connection.
//
#define W3_EVENT_CAL_SSL_EXCEEDED        0xC00008B3L

//
// MessageId: W3_EVENT_NO_MORE_CRASH
//
// MessageText:
//
//  The server stop serving requests for application '%1' because the number of Out of Process
//  component crashes exceed a limit.
//
#define W3_EVENT_NO_MORE_CRASH           0x800008B4L

//
// MessageId: W3_EVENT_FAIL_SHUTDOWN
//
// MessageText:
//
//  The server failed to shut down application '%1'.  The error was '%2'.
//
#define W3_EVENT_FAIL_SHUTDOWN           0x800008B5L

//
// MessageId: W3_EVENT_CANNOT_READ_FILE_EXIST
//
// MessageText:
//
//  The server was unable to read the file %1. The file does not exist.
//
#define W3_EVENT_CANNOT_READ_FILE_EXIST  0x800008B6L

//
// MessageId: W3_EVENT_CANNOT_READ_FILE
//
// MessageText:
//
//  The server was unable to read the file %1. The Windows 32 error returned from the attempt is %2.
//
#define W3_EVENT_CANNOT_READ_FILE        0x800008B7L

//
// MessageId: W3_EVENT_CANNOT_READ_FILE_SIZE
//
// MessageText:
//
//  The server was unable to read the file %1. The file exceeds the maximum allowable size of %2.
//
#define W3_EVENT_CANNOT_READ_FILE_SIZE   0x800008B8L

//
// MessageId: W3_EVENT_CANNOT_READ_FILE_MEMORY
//
// MessageText:
//
//  The server was unable to allocate a buffer to read the file %1.
//
#define W3_EVENT_CANNOT_READ_FILE_MEMORY 0x800008B9L

//
// MessageId: W3_EVENT_FAIL_LOADWAM
//
// MessageText:
//
//  The server failed to load application '%1'.  The error was '%2'.
//
#define W3_EVENT_FAIL_LOADWAM            0x800008BCL

//
// MessageId: W3_EVENT_OOPAPP_VANISHED
//
// MessageText:
//
//  Out of process application '%1' terminated unexpectedly.
//
#define W3_EVENT_OOPAPP_VANISHED         0x800008BDL

//
// MessageId: W3_EVENT_JOB_QUERY_FAILED
//
// MessageText:
//
//  Job object query failed. The data is the error.
//
#define W3_EVENT_JOB_QUERY_FAILED        0xC00008BEL

//
// MessageId: W3_EVENT_JOB_SET_LIMIT_FAILED
//
// MessageText:
//
//  Job object set limit failed. The data is the error.
//
#define W3_EVENT_JOB_SET_LIMIT_FAILED    0xC00008BFL

//
// MessageId: W3_EVENT_JOB_SCEDULE_FAILED
//
// MessageText:
//
//  Schedule a work item for CPU Accounting or Limits failed. The data is the error.
//
#define W3_EVENT_JOB_SCEDULE_FAILED      0xC00008C0L

//
// MessageId: W3_EVENT_JOB_LOGEVENT_LIMIT
//
// MessageText:
//
//  Site '%1' hit its CPU Limit. No action was taken.
//
#define W3_EVENT_JOB_LOGEVENT_LIMIT      0x800008C1L

//
// MessageId: W3_EVENT_JOB_PRIORITY_LIMIT
//
// MessageText:
//
//  Site '%1' hit its CPU Limit. The priority of all process on that site has been lowered to idle class.
//
#define W3_EVENT_JOB_PRIORITY_LIMIT      0x800008C2L

//
// MessageId: W3_EVENT_JOB_PROCSTOP_LIMIT
//
// MessageText:
//
//  Site '%1' hit its CPU Limit. All processes on that site have been terminated.
//
#define W3_EVENT_JOB_PROCSTOP_LIMIT      0x800008C3L

//
// MessageId: W3_EVENT_JOB_PAUSE_LIMIT
//
// MessageText:
//
//  Site '%1' hit its CPU Limit. The site has been paused.
//
#define W3_EVENT_JOB_PAUSE_LIMIT         0x800008C4L

//
// MessageId: SSL_MSG_TIME_INVALID_SERVER_CERT
//
// MessageText:
//
//  The server certificate for instance '%1' has expired or is not yet valid.
//
#define SSL_MSG_TIME_INVALID_SERVER_CERT 0x800008C5L

//
// MessageId: SSL_MSG_REVOKED_SERVER_CERT
//
// MessageText:
//
//  The server certificate for instance '%1' has been revoked.
//
#define SSL_MSG_REVOKED_SERVER_CERT      0x800008C6L

//
// MessageId: SSL_MSG_UNTRUSTED_SERVER_CERT
//
// MessageText:
//
//  The server certificate for instance '%1' does not chain up to a trusted root certificate.
//
#define SSL_MSG_UNTRUSTED_SERVER_CERT    0x800008C7L

//
// MessageId: SSL_MSG_SIGNATURE_INVALID_SERVER_CERT
//
// MessageText:
//
//  One of the certificates in the certificate chain of the server certificate for
//  instance '%1' has an invalid signature.
//
#define SSL_MSG_SIGNATURE_INVALID_SERVER_CERT 0x800008C8L

//
// MessageId: W3_EVENT_JOB_QUEUE_FAILURE
//
// MessageText:
//
//  CPU Limits/Accounting failed to queue work item. The data is the error.
//
#define W3_EVENT_JOB_QUEUE_FAILURE       0x800008C9L

//
// MessageId: SSL_MSG_CERT_MB_ERROR
//
// MessageText:
//
//  The server certificate for instance '%1' had invalid metabase data associated with it and could not be retrieved; the error encountered was '%2'.
//
#define SSL_MSG_CERT_MB_ERROR            0x800008CAL

//
// MessageId: SSL_MSG_CERT_CAPI_ERROR
//
// MessageText:
//
//  A CryptoAPI error was encountered trying to retrieve the server certificate for instance '%1'; the error encountered was '%2'.
//
#define SSL_MSG_CERT_CAPI_ERROR          0x800008CBL

//
// MessageId: SSL_MSG_CERT_NOT_FOUND
//
// MessageText:
//
//  The server certificate for instance '%1' could not be retrieved because it could not be found in a certificate store; the error encountered was '%2'
//
#define SSL_MSG_CERT_NOT_FOUND           0x800008CCL

//
// MessageId: SSL_MSG_CERT_INTERNAL_ERROR
//
// MessageText:
//
//  The server certificate for instance '%1' could not be retrieved due to an internal error; the error encountered was '%2'.
//
#define SSL_MSG_CERT_INTERNAL_ERROR      0x800008CDL

//
// MessageId: SSL_MSG_CTL_MB_ERROR
//
// MessageText:
//
//  The server Certificate Trust List for instance '%1' had invalid metabase data associated with it and could not be retrieved; the error encountered was '%2'.
//
#define SSL_MSG_CTL_MB_ERROR             0x800008CEL

//
// MessageId: SSL_MSG_CTL_CAPI_ERROR
//
// MessageText:
//
//  A CryptoAPI error was encountered trying to retrieve the server Certificate Trust List for instance '%1'; the error encountered was '%2'.
//
#define SSL_MSG_CTL_CAPI_ERROR           0x800008CFL

//
// MessageId: SSL_MSG_CTL_NOT_FOUND
//
// MessageText:
//
//  The server Certificate Trust List for instance '%1' could not be retrieved because it could not be found in a certificate store; the error encountered was '%2'.
//
#define SSL_MSG_CTL_NOT_FOUND            0x800008D0L

//
// MessageId: SSL_MSG_CTL_INTERNAL_ERROR
//
// MessageText:
//
//  The server certificate for instance '%1' could not be retrieved due to an internal error; the error number is '%2'.
//
#define SSL_MSG_CTL_INTERNAL_ERROR       0x800008D1L

//
// MessageId: W3_EVENT_FAILED_CLOSE_CC_SHUTDOWN
//
// MessageText:
//
//  The server failed to close client connections to the following URLs during shutdown: 
//  '%1'.
//
#define W3_EVENT_FAILED_CLOSE_CC_SHUTDOWN 0x800008D2L

//
// MessageId: W3_EVENT_FAIL_OOP_ACTIVATION
//
// MessageText:
//
//  The COM Application '%1' at '%2' failed to activate out of process.
//
#define W3_EVENT_FAIL_OOP_ACTIVATION     0xC00008D3L

//
// MessageId: W3_MSG_READ_RAW_MUST_USE_STANDARD_APPLICATION_MODE
//
// MessageText:
//
//  An attempt was made to load filter '%1' but it requires the
//  SF_NOTIFY_READ_RAW_DATA filter notification and this notification is not
//  supported in Worker Process Isolation Mode.
//
#define W3_MSG_READ_RAW_MUST_USE_STANDARD_APPLICATION_MODE 0xC00008D5L

//
// MessageId: W3_EVENT_UNHEALTHY_ISAPI
//
// MessageText:
//
//  ISAPI '%1' reported itself as unhealthy for the following reason: '%2'.
//
#define W3_EVENT_UNHEALTHY_ISAPI         0x800008D6L

//
// MessageId: W3_EVENT_UNHEALTHY_ISAPI_NO_REASON
//
// MessageText:
//
//  ISAPI '%1' reported itself as unhealthy.  No reason was given by the ISAPI.
//
#define W3_EVENT_UNHEALTHY_ISAPI_NO_REASON 0x800008D7L

//
// MessageId: W3_EVENT_COMPRESSION_DIRECTORY_INVALID
//
// MessageText:
//
//  The directory specified for caching compressed content %1 is invalid.  Static compression is being disabled.
//
#define W3_EVENT_COMPRESSION_DIRECTORY_INVALID 0x800008D8L

//
// MessageId: W3_EVENT_SUBAUTH_REGISTRY_CONFIGURATION_LOCAL
//
// MessageText:
//
//  The registry key for IIS subauthenticator is not configured correctly on local machine, the anonymous password sync feature is disabled.
//
#define W3_EVENT_SUBAUTH_REGISTRY_CONFIGURATION_LOCAL 0x800008D9L

//
// MessageId: W3_EVENT_SUBAUTH_LOCAL_SYSTEM
//
// MessageText:
//
//  The account that the current worker process is running under does not have SeTcbPrivilege privilege, the anonymous password sync feature and the Digest authentication feature are disabled.
//
#define W3_EVENT_SUBAUTH_LOCAL_SYSTEM    0x800008DAL

//
// MessageId: W3_EVENT_RAW_FILTER_CANNOT_BE_STARTED_DUE_TO_HTTPFILTER
//
// MessageText:
//
//  Raw ISAPI Filter could not be loaded due to configuration problem. HTTPFilter Service has to be hosted in inetinfo.exe for Raw ISAPI filters to work correctly. The most likely reason is that IIS5IsolationModeEnabled setting was changed and HTTPFilter service was not restarted. Restart HTTPFilter for configuration changes to be taken into effect.
//
#define W3_EVENT_RAW_FILTER_CANNOT_BE_STARTED_DUE_TO_HTTPFILTER 0xC00008DBL

//
// MessageId: W3_EVENT_ALL_FILTERS_DID_NOT_LOAD
//
// MessageText:
//
//  Could not load all ISAPI filters for site/service.  Therefore startup aborted.
//
#define W3_EVENT_ALL_FILTERS_DID_NOT_LOAD 0xC00008DCL

//
// MessageId: W3_EVENT_FAIL_INITIALIZING_ULATQ
//
// MessageText:
//
//  The worker process failed to initialize the http.sys communication or the w3svc communication layer and therefore could not be started.  The data field contains the error number.
//
#define W3_EVENT_FAIL_INITIALIZING_ULATQ 0xC00008DDL

//
// MessageId: W3_EVENT_CERTIFICATE_MAPPING_COULD_NOT_BE_LOADED
//
// MessageText:
//
//  IIS Client certificate mapping configuration for site %1 failed to be loaded. The data field contains the error number.
//
#define W3_EVENT_CERTIFICATE_MAPPING_COULD_NOT_BE_LOADED 0xC00008DEL

//
// MessageId: W3_EVENT_LOGGING_MODULE_FAILED_TO_LOAD
//
// MessageText:
//
//  Could not initialize the logging module for site %1.  The site will therefore be non-functional.
//
#define W3_EVENT_LOGGING_MODULE_FAILED_TO_LOAD 0xC00008DFL

//
// MessageId: W3_EVENT_SUBAUTH_REGISTRY_CONFIGURATION_DC
//
// MessageText:
//
//  The registry key for IIS subauthenticator is not configured correctly on domain controller, the Digest feature is disabled.
//
#define W3_EVENT_SUBAUTH_REGISTRY_CONFIGURATION_DC 0x800008E0L

//
// MessageId: W3_EVENT_NO_METABASE
//
// MessageText:
//
//  Worker process could not access metabase due to disconnection error.  Marking process as unhealthy.
//
#define W3_EVENT_NO_METABASE             0x800008E1L


#endif  // _W3MSG_H_

/*++

Copyright (c) 1998-2000 Microsoft Corporation

Module Name:

    wasmsg.h

Abstract:

    The IIS World Wide Web Publishing Service worker event log messages. This file is
    MACHINE GENERATED from the wasmsg.mc message file.

Author:

    Seth Pollack (sethp)        08-Jun-1999

Revision History:

--*/


#ifndef _WASMSG_H_
#define _WASMSG_H_


//
// BUGBUG Review all of these messages (severity levels, clarity and accuracy of text, etc.)
//

//
// MessageId: WAS_EVENT_INETINFO_MONITOR_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service's inetinfo process monitor encountered an error and has shut down.  This condition prevents the World Wide Web Publishing Service from detecting an unexpected termination of the inetinfo process and, therefore, may not detect changes to the metabase as expected.  It is recommended that you restart the World Wide Web Publishing Service.   
//
#define WAS_EVENT_INETINFO_MONITOR_FAILED 0x800003E9L

//
// MessageId: WAS_EVENT_RAPID_FAIL_PROTECTION
//
// MessageText:
//
//  Application pool '%1' is being automatically disabled due to a series of failures in the process(es) serving that application pool.
//
#define WAS_EVENT_RAPID_FAIL_PROTECTION  0xC00003EAL

//
// MessageId: WAS_EVENT_BINDING_FAILURE_INVALID_URL
//
// MessageText:
//
//  Cannot register the URL prefix '%1' for site '%2'. The URL may be invalid. The site has been deactivated.  The data field contains the error number.
//
#define WAS_EVENT_BINDING_FAILURE_INVALID_URL 0xC00003EBL

//
// MessageId: WAS_EVENT_BINDING_FAILURE_GENERIC
//
// MessageText:
//
//  Cannot register the URL prefix '%1' for site '%2'. The site has been deactivated.  The data field contains the error number.
//
#define WAS_EVENT_BINDING_FAILURE_GENERIC 0xC00003ECL

//
// MessageId: WAS_EVENT_ERROR_SHUTDOWN
//
// MessageText:
//
//  The World Wide Web Publishing Service is exiting due to an error. The data field contains the error number.
//
#define WAS_EVENT_ERROR_SHUTDOWN         0xC00003EDL

//
// MessageId: WAS_EVENT_SITE_START_FAILED_DUE_TO_PRO_LIMIT
//
// MessageText:
//
//  Virtual Site '%1' can not be started because IIS's running virtual site limit for this operating system platform has all ready been met.  To start this virtual site you must stop all other running virtual sites first.
//
#define WAS_EVENT_SITE_START_FAILED_DUE_TO_PRO_LIMIT 0xC00003EEL

//
// MessageId: WAS_EVENT_BINDING_FAILURE_CONFLICT
//
// MessageText:
//
//  Cannot register the URL prefix '%1' for site '%2'. The necessary network binding may already be in use. The site has been deactivated.  The data field contains the error number.
//
#define WAS_EVENT_BINDING_FAILURE_CONFLICT 0xC00003EFL

//
// MessageId: WAS_EVENT_MAX_CONNECTIONS_GREATER_THAN_PRO_MAX
//
// MessageText:
//
//  Virtual Site '%1' is configured with MaxConnections equal to '%2'.  On this operating system platform IIS only supports 40 connections per site, therefore the site will be configured to have at most 40 connections at any one time.
//
#define WAS_EVENT_MAX_CONNECTIONS_GREATER_THAN_PRO_MAX 0x800003F0L

//
// MessageId: WAS_EVENT_WORKER_PROCESS_CRASH
//
// MessageText:
//
//  A process serving application pool '%1' terminated unexpectedly. The process id was '%2'. The process exit code was '0x%3'.
//
#define WAS_EVENT_WORKER_PROCESS_CRASH   0x800003F1L

//
// MessageId: WAS_EVENT_WORKER_PROCESS_PING_FAILURE
//
// MessageText:
//
//  A process serving application pool '%1' failed to respond to a ping. The process id was '%2'.
//
#define WAS_EVENT_WORKER_PROCESS_PING_FAILURE 0x800003F2L

//
// MessageId: WAS_EVENT_WORKER_PROCESS_IPM_ERROR
//
// MessageText:
//
//  A process serving application pool '%1' suffered a fatal communication error with the World Wide Web Publishing Service. The process id was '%2'. The data field contains the error number. 
//
#define WAS_EVENT_WORKER_PROCESS_IPM_ERROR 0x800003F3L

//
// MessageId: WAS_EVENT_WORKER_PROCESS_STARTUP_TIMEOUT
//
// MessageText:
//
//  A process serving application pool '%1' exceeded time limits during start up. The process id was '%2'. 
//
#define WAS_EVENT_WORKER_PROCESS_STARTUP_TIMEOUT 0x800003F4L

//
// MessageId: WAS_EVENT_WORKER_PROCESS_SHUTDOWN_TIMEOUT
//
// MessageText:
//
//  A process serving application pool '%1' exceeded time limits during shut down. The process id was '%2'. 
//
#define WAS_EVENT_WORKER_PROCESS_SHUTDOWN_TIMEOUT 0x800003F5L

//
// MessageId: WAS_EVENT_WORKER_PROCESS_INTERNAL_ERROR
//
// MessageText:
//
//  The World Wide Web Publishing Service encountered an internal error in its process management of worker process '%2' serving application pool '%1'. The data field contains the error number. 
//
#define WAS_EVENT_WORKER_PROCESS_INTERNAL_ERROR 0x800003F6L

//
// MessageId: WAS_EVENT_ORPHAN_ACTION_FAILED
//
// MessageText:
//
//  A process serving application pool '%1' was orphaned but the specified orphan action %2 could not be executed. The data field contains the error number.
//
#define WAS_EVENT_ORPHAN_ACTION_FAILED   0xC00003F7L

//
// MessageId: WAS_EVENT_LOGGING_FAILURE
//
// MessageText:
//
//  Unable to configure logging for site '%1'. The data field contains the error number.
//
#define WAS_EVENT_LOGGING_FAILURE        0x800003F8L

//
// MessageId: WAS_EVENT_WP_FAILURE_BC
//
// MessageText:
//
//  The World Wide Web Publishing Service has terminated due to a Worker process failure.
//
#define WAS_EVENT_WP_FAILURE_BC          0xC00003F9L

//
// MessageId: WAS_PERF_COUNTER_INITIALIZATION_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service was not able to initialize performance counters. The service will run without the performance counters. Please restart the World Wide Web Publishing Service to reinitialize the performance counters. The data field contains the error number.
//
#define WAS_PERF_COUNTER_INITIALIZATION_FAILURE 0xC00003FAL

//
// MessageId: WAS_PERF_COUNTER_TIMER_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service encountered difficulty initializing performance counters.  Performance counters will function, however, not all counter data may be accurate. The data field contains the error number.
//
#define WAS_PERF_COUNTER_TIMER_FAILURE   0x800003FBL

//
// MessageId: WAS_HTTP_CONTROL_CHANNEL_CONFIG_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service encountered difficulty configuring the HTTP.SYS control channel property '%1'.  The data field contains the error number.
//
#define WAS_HTTP_CONTROL_CHANNEL_CONFIG_FAILED 0xC00003FCL

//
// MessageId: WAS_EVENT_PROCESS_IDENTITY_FAILURE
//
// MessageText:
//
//  The identity of application pool, '%1' is invalid.  If it remains invalid when the first request for the application pool is processed, the application pool will be disabled.  The data field contains the error number.
//
#define WAS_EVENT_PROCESS_IDENTITY_FAILURE 0x800003FDL

//
// MessageId: WAS_EVENT_FAILED_PROCESS_CREATION
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to create a worker process for the application pool '%1'. The data field contains the error number.
//
#define WAS_EVENT_FAILED_PROCESS_CREATION 0x800003FEL

//
// MessageId: NOT_USED_1023
//
// MessageText:
//
//  Not Used.
//
#define NOT_USED_1023                    0xC00003FFL

//
// MessageId: WAS_LOG_FILE_TRUNCATE_SIZE
//
// MessageText:
//
//  Virtual site '%1' is configured to truncate its log every '%2' bytes. Since this value must be at least 1048576 bytes ( 1 megabyte ), 1048576 bytes will be used.  
//
#define WAS_LOG_FILE_TRUNCATE_SIZE       0xC0000400L

//
// MessageId: WAS_EVENT_JOB_LIMIT_HIT
//
// MessageText:
//
//  Application pool '%1' exceeded its job limit settings.  
//
#define WAS_EVENT_JOB_LIMIT_HIT          0x80000401L

//
// MessageId: WAS_EVENT_APP_POOL_HANDLE_NOT_SECURED
//
// MessageText:
//
//  An error occurred securing the handle of application pool '%1'. Therefore, the application pool was not secured as expected. Change the identification information to cause the World Wide Web Publishing Service to secure the handle of the application pool again. The data field contains the error number.
//
#define WAS_EVENT_APP_POOL_HANDLE_NOT_SECURED 0xC0000402L

//
// MessageId: WAS_EVENT_APP_POOL_ENABLE_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service's request of HTTP.SYS to enable the application pool '%1' failed. The data field contains the error number.
//
#define WAS_EVENT_APP_POOL_ENABLE_FAILED 0xC0000403L

//
// MessageId: WAS_EVENT_WP_NOT_ADDED_TO_JOBOBJECT
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to add the worker process '%1' to the job object representing application pool '%2'.  The data field contains the error number.
//
#define WAS_EVENT_WP_NOT_ADDED_TO_JOBOBJECT 0xC0000404L

//
// MessageId: WAS_EVENT_BINDING_FAILURE_2
//
// MessageText:
//
//  A failure occurred while configuring an application's bindings for site '%1'.  The site has been deactivated.  The data field contains the error number.
//
#define WAS_EVENT_BINDING_FAILURE_2      0xC0000405L

//
// MessageId: WAS_EVENT_INETINFO_CRASH_SHUTDOWN
//
// MessageText:
//
//  Inetinfo terminated unexpectedly and the system was not configured to restart IIS Admin.  The World Wide Web Publishing Service has shut down.
//
#define WAS_EVENT_INETINFO_CRASH_SHUTDOWN 0xC0000406L

//
// MessageId: NOT_USED_1031
//
// MessageText:
//
//  Not Used.
//
#define NOT_USED_1031                    0xC0000407L

//
// MessageId: WAS_EVENT_LOG_DIRECTORY_MAPPED_NETWORK_DRIVE
//
// MessageText:
//
//  A failure occurred while configuring the logging properties for the site '%1'. Probable cause: A mapped network path is being used for the site's log file directory path, which is not supported by IIS.  Please use a UNC path instead.
//
#define WAS_EVENT_LOG_DIRECTORY_MAPPED_NETWORK_DRIVE 0xC0000408L

//
// MessageId: WAS_EVENT_LOG_DIRECTORY_MACHINE_OR_SHARE_INVALID
//
// MessageText:
//
//  A failure occurred while configuring the logging properties for the site '%1'.  Probable cause: The site's log file directory contains an invalid machine or share name.
//
#define WAS_EVENT_LOG_DIRECTORY_MACHINE_OR_SHARE_INVALID 0xC0000409L

//
// MessageId: WAS_EVENT_LOG_DIRECTORY_ACCESS_DENIED
//
// MessageText:
//
//  A failure occurred while configuring the logging properties for the site '%1'.  The server does not have access permissions to the site's log file directory.
//
#define WAS_EVENT_LOG_DIRECTORY_ACCESS_DENIED 0xC000040AL

//
// MessageId: WAS_EVENT_LOG_DIRECTORY_NOT_FULLY_QUALIFIED
//
// MessageText:
//
//  A failure occurred while configuring the logging properties for the site '%1'.  The site's log file directory is not fully qualified.  Probable cause: It is missing the drive letter or other crucial information. 
//
#define WAS_EVENT_LOG_DIRECTORY_NOT_FULLY_QUALIFIED 0xC000040BL

//
// MessageId: WAS_CONFIG_MANAGER_INITIALIZATION_FAILED
//
// MessageText:
//
//  A failure occurred while initializing the configuration manager for the World Wide Web Publishing Service. The data field contains the error number.
//
#define WAS_CONFIG_MANAGER_INITIALIZATION_FAILED 0xC000040CL

//
// MessageId: WAS_HTTP_CONTROL_CHANNEL_OPEN_FAILED
//
// MessageText:
//
//  A failure occurred while opening the HTTP control channel for the World Wide Web Publishing Service. The data field contains the error number.
//
#define WAS_HTTP_CONTROL_CHANNEL_OPEN_FAILED 0xC000040DL

//
// MessageId: NOT_USED_1038
//
// MessageText:
//
//  Not Used.
//
#define NOT_USED_1038                    0xC000040EL

//
// MessageId: WAS_EVENT_WORKER_PROCESS_BAD_HRESULT
//
// MessageText:
//
//  A process serving application pool '%1' reported a failure. The process id was '%2'.  The data field contains the error number.
//
#define WAS_EVENT_WORKER_PROCESS_BAD_HRESULT 0xC000040FL

//
// MessageId: NOT_USED_1040
//
// MessageText:
//
//  Not Used.
//
#define NOT_USED_1040                    0xC0000410L

//
// MessageId: WAS_EVENT_WMS_RANGE_ERROR
//
// MessageText:
//
//  The '%1' '%2' failed range validation for property '%3'.  The configured value '%4' is outside of the range '%5' to '%6'.  The value will default to '%7'.
//
#define WAS_EVENT_WMS_RANGE_ERROR        0x80000411L

//
// MessageId: WAS_EVENT_WMS_APP_POOL_COMMAND_ERROR
//
// MessageText:
//
//  The AppPoolCommand property set on the application pool '%1' is not a valid value.  It is '%2'.  It must be either MD_APPPOOL_COMMAND_START = 1 or MD_APPPOOL_COMMAND_STOP = 2.
//
#define WAS_EVENT_WMS_APP_POOL_COMMAND_ERROR 0x80000412L

//
// MessageId: WAS_EVENT_WMS_SITE_BINDING_ERROR
//
// MessageText:
//
//  The virtual site '%1' has been invalidated and will be ignored because valid site bindings could not be constructed, or no site bindings exist.
//
#define WAS_EVENT_WMS_SITE_BINDING_ERROR 0x80000413L

//
// MessageId: WAS_EVENT_WMS_SITE_APP_POOL_ID_ERROR
//
// MessageText:
//
//  The virtual site '%1' has been invalidated and will be ignored because the site's AppPoolId is null.
//
#define WAS_EVENT_WMS_SITE_APP_POOL_ID_ERROR 0x80000414L

//
// MessageId: NOT_USED_1045
//
// MessageText:
//
//  Not Used.
//
#define NOT_USED_1045                    0x80000415L

//
// MessageId: WAS_EVENT_WMS_SERVER_COMMAND_ERROR
//
// MessageText:
//
//  The server command property for virtual site '%1' is not a valid value.  It is set to '%2'.  It must be one of the following:  MD_SERVER_COMMAND_START = 1 or MD_SERVER_COMMAND_STOP = 2 or MD_SERVER_COMMAND_PAUSE = 3 or MD_SERVER_COMMAND_CONTINUE = 4.
//
#define WAS_EVENT_WMS_SERVER_COMMAND_ERROR 0x80000416L

//
// MessageId: WAS_EVENT_WMS_APPLICATION_APP_POOL_ID_EMPTY_ERROR
//
// MessageText:
//
//  The application '%2' belonging to site '%1' has an AppPoolId set, but the property is empty.  Therefore, the application will be ignored.
//
#define WAS_EVENT_WMS_APPLICATION_APP_POOL_ID_EMPTY_ERROR 0x80000417L

//
// MessageId: WAS_EVENT_WMS_APPLICATION_APP_POOL_ID_INVALID_ERROR
//
// MessageText:
//
//  The application '%2' belonging to site '%1' has an invalid AppPoolId '%3' set.  Therefore, the application will be ignored.
//
#define WAS_EVENT_WMS_APPLICATION_APP_POOL_ID_INVALID_ERROR 0x80000418L

//
// MessageId: WAS_EVENT_WMS_IDLE_GREATER_RESTART_ERROR
//
// MessageText:
//
//  The application pool '%1' has an IdleTimeout '%2' greater than the PeriodicRestartTime '%3'.  The defaults ( IdleTimeout = '%4' & PeriodicRestartTime '%5' ) will be used.
//
#define WAS_EVENT_WMS_IDLE_GREATER_RESTART_ERROR 0x80000419L

//
// MessageId: WAS_EVENT_WMS_APP_POOL_ID_TOO_LONG_ERROR
//
// MessageText:
//
//  The application pool id '%1' exceeds length limits.  It is '%2' characters and can not be more than '%3' characters.  The application pool will therefore be ignored.
//
#define WAS_EVENT_WMS_APP_POOL_ID_TOO_LONG_ERROR 0x8000041AL

//
// MessageId: WAS_EVENT_WMS_APP_POOL_ID_NULL_ERROR
//
// MessageText:
//
//  An application pool id was defined as a zero length string.  An application pool id must not be a zero length string. The application pool will therefore be ignored.
//
#define WAS_EVENT_WMS_APP_POOL_ID_NULL_ERROR 0x8000041BL

//
// MessageId: WAS_EVENT_WMS_APPLICATION_SITE_INVALID_ERROR
//
// MessageText:
//
//  The application '%2' belongs to an invalid site '%1'.  Therefore, the application will be ignored.
//
#define WAS_EVENT_WMS_APPLICATION_SITE_INVALID_ERROR 0x8000041CL

//
// MessageId: WAS_EVENT_WMS_FAILED_TO_PROCESS_CHANGE_NOTIFICATION
//
// MessageText:
//
//  The World Wide Web Publishing Service received a change notification, but was unable to process it correctly.  The data field contains the error number.
//
#define WAS_EVENT_WMS_FAILED_TO_PROCESS_CHANGE_NOTIFICATION 0xC000041DL

//
// MessageId: WAS_EVENT_AUTO_SHUTDOWN_ACTION_FAILED_1
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to run the auto stop action %2 for application pool '%1'. The data field contains the error number.
//
#define WAS_EVENT_AUTO_SHUTDOWN_ACTION_FAILED_1 0xC000041EL

//
// MessageId: WAS_EVENT_WMS_SITE_APPPOOL_INVALID_ERROR
//
// MessageText:
//
//  The site '%1' was disabled because the application pool defined for the site '%2' is not a valid application pool.
//
#define WAS_EVENT_WMS_SITE_APPPOOL_INVALID_ERROR 0x8000041FL

//
// MessageId: WAS_EVENT_WMS_SITE_ROOT_APPPOOL_INVALID_ERROR
//
// MessageText:
//
//  The site '%1' was disabled because the application pool '%2' defined for the site's root application is not a valid application pool.
//
#define WAS_EVENT_WMS_SITE_ROOT_APPPOOL_INVALID_ERROR 0x80000420L

//
// MessageId: WAS_EVENT_FAILED_PROCESS_CREATION_NO_ID
//
// MessageText:
//
//  The identity of application pool '%1' is invalid, so the World Wide Web Publishing Service can not create a worker process to serve the application pool.  Therefore, the application pool has been disabled.
//
#define WAS_EVENT_FAILED_PROCESS_CREATION_NO_ID 0x80000421L

//
// MessageId: WAS_EVENT_FAILED_PROCESS_AFFINITY_SETTING
//
// MessageText:
//
//  The World Wide Web Publishing Service encountered a failure while setting the affinity mask of application pool '%1'.  Probable cause:  The mask does not contain any processors available on this machine.  The data field contains the error number.
//
#define WAS_EVENT_FAILED_PROCESS_AFFINITY_SETTING 0x80000422L

//
// MessageId: WAS_EVENT_RAPID_FAIL_PROTECTION_REGARDLESS
//
// MessageText:
//
//  A failure was encountered while launching the process serving application pool '%1'. The application pool has been disabled.
//
#define WAS_EVENT_RAPID_FAIL_PROTECTION_REGARDLESS 0xC0000423L

//
// MessageId: WAS_EVENT_JOB_OBJECT_UPDATE_FAILED
//
// MessageText:
//
//  The job object associated with application pool '%1' encountered an error during configuration.  CPU monitoring may not function as expected.  The data field contains the error number.
//
#define WAS_EVENT_JOB_OBJECT_UPDATE_FAILED 0xC0000424L

//
// MessageId: WAS_EVENT_JOB_OBJECT_TIMER_START_FAILED
//
// MessageText:
//
//  The job object attached to application pool '%1' failed to start its timer.  The application pool's CPU usage is being monitored and will eventually reach the limit and report a failure.  The data field contains the error number.
//
#define WAS_EVENT_JOB_OBJECT_TIMER_START_FAILED 0xC0000425L

//
// MessageId: WAS_HTTP_CONTROL_CHANNEL_LOGGING_CONFIG_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service encountered a failure configuring the logging properties on the HTTP Control Channel. Logging Enabled is '%1'.  Log File Directory is '%2'.  Log Period is '%3'.  Log Truncate Size is '%4'. The data field contains the error number.
//
#define WAS_HTTP_CONTROL_CHANNEL_LOGGING_CONFIG_FAILED 0xC0000426L

//
// MessageId: WAS_EVENT_NOTIFICATION_HOOKUP_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service encountered a failure requesting metabase change notifications.  The data field contains the error number.
//
#define WAS_EVENT_NOTIFICATION_HOOKUP_FAILURE 0xC0000427L

//
// MessageId: WAS_EVENT_NOTIFICATION_REHOOKUP_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service encountered a failure requesting metabase change notifications during recovery from inetinfo terminating unexpectedly. While the World Wide Web Publishing Service will continue to run, it is highly probable that it is no longer using current metabase data. Please restart the World Wide Web Publishing Service to correct this condition.  The data field contains the error number.
//
#define WAS_EVENT_NOTIFICATION_REHOOKUP_FAILURE 0xC0000428L

//
// MessageId: WAS_GLOBAL_LOG_FILE_TRUNCATE_SIZE
//
// MessageText:
//
//  Centralized logging is configured to truncate its log every '%1' bytes. Since this value must be at least 1048576 bytes ( 1 megabyte ), 1048576 bytes will be used.  
//
#define WAS_GLOBAL_LOG_FILE_TRUNCATE_SIZE 0x80000429L

//
// MessageId: WAS_CENTRALIZED_LOGGING_NOT_CONFIGURED
//
// MessageText:
//
//  The World Wide Web Publishing Service encountered an error attempting to configure centralized logging. It is not configured as expected. The data field contains the error number. 
//
#define WAS_CENTRALIZED_LOGGING_NOT_CONFIGURED 0xC000042AL

//
// MessageId: WAS_EVENT_WMS_GLOBAL_RANGE_ERROR
//
// MessageText:
//
//  The World Wide Web Publishing Service property '%1' failed range validation. The configured value, '%2' is outside of the range '%3' to '%4'. The default value, '%5', will be used.
//
#define WAS_EVENT_WMS_GLOBAL_RANGE_ERROR 0x8000042BL

//
// MessageId: WAS_EVENT_RECORD_SITE_STATE_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to record the proper state '%2' and win32error '%3' of site '%1'in the metabase. To correct, start/stop the site or restart the World Wide Web Publishing Service. The data field contains the error number.
//
#define WAS_EVENT_RECORD_SITE_STATE_FAILURE 0x8000042CL

//
// MessageId: WAS_EVENT_RECORD_APP_POOL_STATE_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to record the proper state '%2' and win32error '%3' of application pool '%1' in the metabase. To correct, start/stop the application pool or restart the World Wide Web Publishing Service. The data field contains the error number.
//
#define WAS_EVENT_RECORD_APP_POOL_STATE_FAILURE 0x8000042DL

//
// MessageId: WAS_EVENT_RECYCLE_APP_POOL_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to issue recycle requests to all worker processes of application pool '%1'.  The data field contains the error number.
//
#define WAS_EVENT_RECYCLE_APP_POOL_FAILURE 0x8000042EL

//
// MessageId: WAS_HTTP_PSCHED_NOT_INSTALLED_SITE
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to enable bandwidth throttling on site '%1' because QoS Packet Scheduler is not installed.
//
#define WAS_HTTP_PSCHED_NOT_INSTALLED_SITE 0x8000042FL

//
// MessageId: WAS_HTTP_CONFIG_GROUP_BANDWIDTH_SETTING_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to enable bandwidth throttling on site '%1'.  The data field contains the error number.
//
#define WAS_HTTP_CONFIG_GROUP_BANDWIDTH_SETTING_FAILED 0x80000430L

//
// MessageId: WAS_HTTP_PSCHED_NOT_INSTALLED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to enable global bandwidth throttling because QoS Packet Scheduler is not installed.
//
#define WAS_HTTP_PSCHED_NOT_INSTALLED    0x80000431L

//
// MessageId: WAS_EVENT_RECYCLE_WP_TIME
//
// MessageText:
//
//  A worker process with process id of '%1' serving application pool '%2' has requested a recycle because the worker process reached its allowed processing time limit.  
//
#define WAS_EVENT_RECYCLE_WP_TIME        0x40000432L

//
// MessageId: WAS_EVENT_RECYCLE_WP_REQUEST_COUNT
//
// MessageText:
//
//  A worker process with process id of '%1' serving application pool '%2' has requested a recycle because it reached its allowed request limit.  
//
#define WAS_EVENT_RECYCLE_WP_REQUEST_COUNT 0x40000433L

//
// MessageId: WAS_EVENT_RECYCLE_WP_SCHEDULED
//
// MessageText:
//
//  A worker process with process id of '%1' serving application pool '%2' has requested a recycle because it reached its scheduled recycle time.  
//
#define WAS_EVENT_RECYCLE_WP_SCHEDULED   0x40000434L

//
// MessageId: WAS_EVENT_RECYCLE_WP_MEMORY
//
// MessageText:
//
//  A worker process with process id of '%1' serving application pool '%2' has requested a recycle because it reached its virtual memory limit.  
//
#define WAS_EVENT_RECYCLE_WP_MEMORY      0x40000435L

//
// MessageId: WAS_EVENT_RECYCLE_WP_ISAPI
//
// MessageText:
//
//  An ISAPI reported an unhealthy condition to its worker process. Therefore, the worker process with process id of '%1' serving application pool '%2' has requested a recycle.  
//
#define WAS_EVENT_RECYCLE_WP_ISAPI       0x40000436L

//
// MessageId: WAS_EVENT_RECYCLE_POOL_ADMIN_REQUESTED
//
// MessageText:
//
//  An administrator has requested a recycle of all worker processes in application pool '%1'.
//
#define WAS_EVENT_RECYCLE_POOL_ADMIN_REQUESTED 0x40000437L

//
// MessageId: WAS_EVENT_RECYCLE_POOL_CONFIG_CHANGE
//
// MessageText:
//
//  The worker processes serving application pool '%1' are being recycled due to 1 or more configuration changes in the application pool properties which necessitate a restart of the processes.
//
#define WAS_EVENT_RECYCLE_POOL_CONFIG_CHANGE 0x40000438L

//
// MessageId: WAS_EVENT_RECYCLE_POOL_RECOVERY
//
// MessageText:
//
//  The worker processes serving application pool '%1' are being recycled due to detected problems with the metabase that may make current cached metadata invalid.
//
#define WAS_EVENT_RECYCLE_POOL_RECOVERY  0x40000439L

//
// MessageId: WAS_IGNORING_WP_FAILURE_DUE_TO_DEBUGGER
//
// MessageText:
//
//  A worker process with pid '%2' that serves application pool '%1' has been determined to be unhealthy (see previous event log message), but because a debugger is attached to it, the World Wide Web Publishing Service will ignore the error.
//
#define WAS_IGNORING_WP_FAILURE_DUE_TO_DEBUGGER 0x4000043AL

//
// MessageId: WAS_HTTP_SITE_COUNTER_SIZE_FAILURE
//
// MessageText:
//
//  HTTP.SYS provided inconsistent site performance counter data to the World Wide Web Publishing Service.  Therefore, the World Wide Web Publishing Service will ignore the data provided. 
//
#define WAS_HTTP_SITE_COUNTER_SIZE_FAILURE 0xC000043BL

//
// MessageId: WAS_EVENT_FAILED_TO_DISABLE_APP_POOL
//
// MessageText:
//
//  The World Wide Web Publishing Service's request of HTTP.SYS to disable the application pool '%1' failed.  The data field contains the error number.
//
#define WAS_EVENT_FAILED_TO_DISABLE_APP_POOL 0xC000043CL

//
// MessageId: WAS_EVENT_FAILED_TO_SET_APP_POOL_CONFIGURATION
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to apply a new configuration for application pool '%1'.  The data field contains the error number.
//
#define WAS_EVENT_FAILED_TO_SET_APP_POOL_CONFIGURATION 0xC000043DL

//
// MessageId: WAS_EVENT_FAILED_TO_SET_LOAD_BALANCER_CAP
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to properly configure the load balancer capabilities on application pool '%1'.  The data field contains the error number.
//
#define WAS_EVENT_FAILED_TO_SET_LOAD_BALANCER_CAP 0xC000043EL

//
// MessageId: WAS_EVENT_FAILED_TO_SET_QUEUE_LENGTH
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to properly configure the application pool queue length on app pool '%1'.  The data field contains the error number.
//
#define WAS_EVENT_FAILED_TO_SET_QUEUE_LENGTH 0xC000043FL

//
// MessageId: WAS_EVENT_FAILED_TO_CONFIGURE_JOB_OBJECT
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to properly configure the job object for application pool '%1'. The data field contains the error number.
//
#define WAS_EVENT_FAILED_TO_CONFIGURE_JOB_OBJECT 0xC0000440L

//
// MessageId: WAS_EVENT_FAILED_TO_WAIT_FOR_DEMAND_START
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to issue a demand start to HTTP.SYS for application pool '%1'.  The data field contains the error number.
//
#define WAS_EVENT_FAILED_TO_WAIT_FOR_DEMAND_START 0xC0000441L

//
// MessageId: WAS_EVENT_FAILED_TO_UPDATE_AUTOSTART_FOR_APPPOOL
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to update the AutoStart property for application pool '%1'.  The data field contains the error number.
//
#define WAS_EVENT_FAILED_TO_UPDATE_AUTOSTART_FOR_APPPOOL 0xC0000442L

//
// MessageId: WAS_EVENT_AUTO_SHUTDOWN_ACTION_FAILED_2
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to run the auto stop action for application pool '%1'.  The data field contains the error number.
//
#define WAS_EVENT_AUTO_SHUTDOWN_ACTION_FAILED_2 0xC0000443L

//
// MessageId: WAS_EVENT_FAILED_TO_ISSUE_REQUEST_FOR_COUNTERS
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to issue a request for the worker process '%2' of application pool '%1' to supply its performance counters. The data field contains the error number.
//
#define WAS_EVENT_FAILED_TO_ISSUE_REQUEST_FOR_COUNTERS 0xC0000444L

//
// MessageId: WAS_EVENT_FAILED_TO_OVERLAP_RECYCLE
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to overlap recycle for application pool '%1' worker process '%2'.  The data field contains the error number.
//
#define WAS_EVENT_FAILED_TO_OVERLAP_RECYCLE 0xC0000445L

//
// MessageId: WAS_EVENT_DISSOCIATE_APPLICATION_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to disassociate the application '%1' from the virtual site '%2'. The data field contains the error number.
//
#define WAS_EVENT_DISSOCIATE_APPLICATION_FAILED 0xC0000446L

//
// MessageId: WAS_EVENT_DELETE_CONFIG_GROUP_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to delete the config group for the application '%1' in site '%2'. The data field contains the error number.
//
#define WAS_EVENT_DELETE_CONFIG_GROUP_FAILED 0xC0000447L

//
// MessageId: WAS_EVENT_REMOVING_ALL_URLS_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to remove the urls for the virtual site '%1'.  The data field contains the error number.
//
#define WAS_EVENT_REMOVING_ALL_URLS_FAILED 0xC0000448L

//
// MessageId: WAS_EVENT_SET_APP_POOL_FOR_CG_IN_HTTP_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to set the application pool for the application '%1' in site '%2'. The data field contains the error number.
//
#define WAS_EVENT_SET_APP_POOL_FOR_CG_IN_HTTP_FAILED 0xC0000449L

//
// MessageId: WAS_EVENT_SET_SITE_MAX_CONNECTIONS_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to set the max connections for the virtual site '%1'.  The data field contains the error number.
//
#define WAS_EVENT_SET_SITE_MAX_CONNECTIONS_FAILED 0xC000044AL

//
// MessageId: WAS_EVENT_SET_SITE_CONNECTION_TIMEOUT_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to set the connection timeout for the virtual site '%1'.  The data field contains the error number.
//
#define WAS_EVENT_SET_SITE_CONNECTION_TIMEOUT_FAILED 0xC000044BL

//
// MessageId: WAS_APPLICATION_CREATE_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to create the application '%2' in site '%1'. The data field contains the error number.
//
#define WAS_APPLICATION_CREATE_FAILED    0xC000044CL

//
// MessageId: WAS_APPPOOL_CREATE_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to create app pool '%1'.  The data field contains the error number.
//
#define WAS_APPPOOL_CREATE_FAILED        0xC000044DL

//
// MessageId: WAS_SITE_CREATE_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to create site '%1'.  The data field contains the error number.
//
#define WAS_SITE_CREATE_FAILED           0xC000044EL

//
// MessageId: WAS_APPLICATION_DELETE_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to delete the application '%2' in site '%1'.  The data field contains the error number.
//
#define WAS_APPLICATION_DELETE_FAILED    0xC000044FL

//
// MessageId: WAS_APPPOOL_DELETE_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to delete app pool '%1'.  The data field contains the error number.
//
#define WAS_APPPOOL_DELETE_FAILED        0xC0000450L

//
// MessageId: WAS_SITE_DELETE_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to delete site '%1'.  The data field contains the error number.
//
#define WAS_SITE_DELETE_FAILED           0xC0000451L

//
// MessageId: WAS_APPLICATION_MODIFY_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to modify the application '%2' in site '%1'.  The data field contains the error number.
//
#define WAS_APPLICATION_MODIFY_FAILED    0xC0000452L

//
// MessageId: WAS_APPPOOL_MODIFY_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to modify app pool '%1'.  The data field contains the error number.
//
#define WAS_APPPOOL_MODIFY_FAILED        0xC0000453L

//
// MessageId: WAS_SITE_MODIFY_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to modify site '%1'.  The data field contains the error number.
//
#define WAS_SITE_MODIFY_FAILED           0xC0000454L

//
// MessageId: WAS_HTTP_CONTROL_CHANNEL_FILTER_CONFIG_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to set the control channel's filter config.  The data field contains the error number.
//
#define WAS_HTTP_CONTROL_CHANNEL_FILTER_CONFIG_FAILED 0xC0000455L

//
// MessageId: WAS_SITE_AUTO_START_WRITE_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to write the AutoStart Property for site '%1'.  The data field contains the error number.
//
#define WAS_SITE_AUTO_START_WRITE_FAILED 0xC0000456L

//
// MessageId: WAS_HTTP_SSL_ENTRY_CLEANUP_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to delete all IIS owned SSL configuration data. The data field contains the error number.
//
#define WAS_HTTP_SSL_ENTRY_CLEANUP_FAILED 0xC0000457L

//
// MessageId: WAS_SSL_QUERY_SITE_CONFIG_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to query SSL configuration data for site '%1'. The data field contains the error number.
//
#define WAS_SSL_QUERY_SITE_CONFIG_FAILED 0xC0000458L

//
// MessageId: WAS_SSL_SET_SITE_CONFIG_COLLISION_IIS
//
// MessageText:
//
//  One of the IP/Port combinations for site '%1' has already be configured to be used by another site.  The other site's SSL configuration will be used.  
//
#define WAS_SSL_SET_SITE_CONFIG_COLLISION_IIS 0xC0000459L

//
// MessageId: WAS_SSL_SET_SITE_CONFIG_COLLISION_OTHER
//
// MessageText:
//
//  One of the IP/Port combinations for site '%1' has already been configured to be used by another program.  The other program's SSL configuration will be used.  
//
#define WAS_SSL_SET_SITE_CONFIG_COLLISION_OTHER 0xC000045AL

//
// MessageId: WAS_SSL_SET_SITE_CONFIG_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to set SSL configuration data for site '%1'. The data field contains the error number.
//
#define WAS_SSL_SET_SITE_CONFIG_FAILED   0xC000045BL

//
// MessageId: WAS_SSL_DELETE_SITE_CONFIG_FAILED
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to delete SSL configuration data for site '%1'. The data field contains the error number.
//
#define WAS_SSL_DELETE_SITE_CONFIG_FAILED 0xC000045CL

//
// MessageId: WAS_EVENT_RECYCLE_WP_MEMORY_PRIVATE_BYTES
//
// MessageText:
//
//  A worker process with process id of '%1' serving application pool '%2' has requested a recycle because it reached its private bytes memory limit.  
//
#define WAS_EVENT_RECYCLE_WP_MEMORY_PRIVATE_BYTES 0x4000045DL

//
// MessageId: WAS_EVENT_WMS_FAILED_TO_DETERMINE_DELETIONS
//
// MessageText:
//
//  During recovery from an unexpected termination of the inetinfo process, the World Wide Web Publishing Service failed to identify the appropriate records requiring deletion from its metadata cache.  The data field contains the error number.
//
#define WAS_EVENT_WMS_FAILED_TO_DETERMINE_DELETIONS 0xC000045EL

//
// MessageId: WAS_EVENT_INETINFO_RESPONSE_FAILED
//
// MessageText:
//
//  During recovery from an unexpected termination of the inetinfo process, the World Wide Web Publishing Service failed to queue action items necessary to handle the recovery.  It is recommended that you restart the World Wide Web Publishing Service. The data field contains the error number.
//
#define WAS_EVENT_INETINFO_RESPONSE_FAILED 0xC000045FL

//
// MessageId: WAS_PERF_COUNTER_HTTP_GLOBALS_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to obtain cache counters from HTTP.SYS.  The reported performance counters do not include performance counters from HTTP.SYS for this gathering.  The data field contains the error number.
//
#define WAS_PERF_COUNTER_HTTP_GLOBALS_FAILURE 0xC0000460L

//
// MessageId: WAS_PERF_COUNTER_HTTP_SITE_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to obtain site performance counters from HTTP.SYS.  The reported performance counters do not include counters from HTTP.SYS for this gathering.  The data field contains the error number.
//
#define WAS_PERF_COUNTER_HTTP_SITE_FAILURE 0xC0000461L

//
// MessageId: WAS_PERF_COUNTER_PUBLISHING_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to publish the performance counters it gathered.  The data field contains the error number.
//
#define WAS_PERF_COUNTER_PUBLISHING_FAILURE 0xC0000462L

//
// MessageId: WAS_PERF_COUNTER_GATHER_TIMER_CANCEL_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to cancel the performance counter gathering timer.  The data field contains the error number.
//
#define WAS_PERF_COUNTER_GATHER_TIMER_CANCEL_FAILURE 0xC0000463L

//
// MessageId: WAS_PERF_COUNTER_TIMER_CANCEL_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to cancel the performance counter timer.  The data field contains the error number.
//
#define WAS_PERF_COUNTER_TIMER_CANCEL_FAILURE 0xC0000464L

//
// MessageId: WAS_PERF_COUNTER_GATHER_TIMER_BEGIN_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to start the performance counter gathering timer.  The data field contains the error number.
//
#define WAS_PERF_COUNTER_GATHER_TIMER_BEGIN_FAILURE 0xC0000465L

//
// MessageId: WAS_EVENT_WMS_FAILED_TO_COPY_CHANGE_NOT
//
// MessageText:
//
//  The World Wide Web Publishing Service failed to copy a change notification for processing. Therefore, the service may not be in sync with the current data in the metabase.  The data field contains the error number.
//
#define WAS_EVENT_WMS_FAILED_TO_COPY_CHANGE_NOT 0xC0000466L

//
// MessageId: WAS_EVENT_WORKER_PROCESS_NOT_TRUSTED
//
// MessageText:
//
//  A worker process '%2' serving application pool '%1' is no longer trusted by the World Wide Web Publishing Service, based on ill-formed data the worker process sent to the service.
//
#define WAS_EVENT_WORKER_PROCESS_NOT_TRUSTED 0xC0000467L

//
// MessageId: WAS_ASP_PERF_COUNTER_INITIALIZATION_FAILURE
//
// MessageText:
//
//  The World Wide Web Publishing Service was not able to initialize asp performance counters.  The service will therefore run without asp performance counters. Restart the World Wide Web Publishing Service to start asp performance counter gathering.  The data field contains the error number.
//
#define WAS_ASP_PERF_COUNTER_INITIALIZATION_FAILURE 0xC0000468L

//
// MessageId: WAS_EVENT_BINDING_FAILURE_INVALID_ADDRESS
//
// MessageText:
//
//  Cannot register the URL prefix '%1' for site '%2'. Either the network endpoint for the site's IP address could not be created, or the IP listen list for HTTP.sys did not contain any usable IP addresses. The site has been deactivated.  The data field contains the error number.
//
#define WAS_EVENT_BINDING_FAILURE_INVALID_ADDRESS 0xC0000469L

//
// MessageId: WAS_EVENT_BINDING_FAILURE_UNREACHABLE
//
// MessageText:
//
//  Cannot register the URL prefix '%1' for site '%2'. The IP address for the site is not in the HTTP.sys IP listen list. The site has been deactivated.  The data field contains the error number.
//
#define WAS_EVENT_BINDING_FAILURE_UNREACHABLE 0xC000046AL

//
// MessageId: WAS_EVENT_BINDING_FAILURE_OUT_OF_SPACE
//
// MessageText:
//
//  Cannot register the URL prefix '%1' for site '%2'. Too many listening ports have been configured in HTTP.sys. The site has been deactivated.  The data field contains the error number.
//
#define WAS_EVENT_BINDING_FAILURE_OUT_OF_SPACE 0xC000046BL


#endif  // _WASMSG_H_

/**********************************************************************/
/**                       Microsoft Windows NT                       **/
/**                Copyright(c) Microsoft Corp., 1993                **/
/**********************************************************************/

/*
    ssincmsg.h

    This file is generated by the MC tool from the SSINCMSG.MC message
    file.


    FILE HISTORY:
        MingLu     11-Apr-1993 Created.

    Note: ssinc messages have been modified the way that all of them
    will ignore file and URL names. It is to assure that there are no security
    issues such as allowing cross site scripting attack or exposing
    physical paths to files
 

*/


#ifndef _SSINCMSG_H_
#define _SSINCMSG_H_

//
// MessageId: SSINCMSG_ERROR_HANDLING_FILE
//
// MessageText:
//
//  <B>Error processing SSI file</B><BR>
//
#define SSINCMSG_ERROR_HANDLING_FILE     0xC00009C5L

//
// MessageId: SSINCMSG_INVALID_TAG
//
// MessageText:
//
//  <B>Invalid SSI Tag</B><BR>
//
#define SSINCMSG_INVALID_TAG             0xC00009C6L

//
// MessageId: SSINCMSG_CANT_DO_FLASTMOD
//
// MessageText:
//
//  <B>Cannot perform flastmod(): Win32 Error Code = %2!.20s!</B><BR>
//
#define SSINCMSG_CANT_DO_FLASTMOD        0xC00009C7L

//
// MessageId: SSINCMSG_CANT_DO_FSIZE
//
// MessageText:
//
//  <B>Cannot perform fsize(): Win32 Error Code = %2!.20s!</B><BR>
//
#define SSINCMSG_CANT_DO_FSIZE           0xC00009C8L

//
// MessageId: SSINCMSG_CANT_FIND_VARIABLE
//
// MessageText:
//
//  <B>Variable '%1!.40s!' cannot be found</B><BR>
//
#define SSINCMSG_CANT_FIND_VARIABLE      0xC00009C9L

//
// MessageId: SSINCMSG_CANT_EVALUATE_VARIABLE
//
// MessageText:
//
//  <B>Variable '%1!.40s!' cannot be evaluated</B><BR>
//
#define SSINCMSG_CANT_EVALUATE_VARIABLE  0xC00009CAL

//
// MessageId: SSINCMSG_NOT_SUPPORTED
//
// MessageText:
//
//  <B>SSI feature not supported</B><BR>
//
#define SSINCMSG_NOT_SUPPORTED           0xC00009CBL

//
// MessageId: SSINCMSG_REQUEST_ERROR
//
// MessageText:
//
//  <B>Error handling SSI File :  Win32 Error Code = %2!.20s!</B><BR>
//
#define SSINCMSG_REQUEST_ERROR           0xC00009CCL

//
// MessageId: SSINCMSG_LOG_ERROR
//
// MessageText:
//
//  <B>Failed to process SSI file</B><BR>
//
#define SSINCMSG_LOG_ERROR               0xC00009CDL

//
// MessageId: SSINCMSG_CANT_EXEC_CMD
//
// MessageText:
//
//  <B>Failed to execute CMD :  Win32 Error Code = %2!.20s!</B><BR>
//
#define SSINCMSG_CANT_EXEC_CMD           0xC00009CEL

//
// MessageId: SSINCMSG_CANT_EXEC_CGI
//
// MessageText:
//
//  <B>Failed to execute CGI :  Win32 Error Code = %2!.20s!</B><BR>
//
#define SSINCMSG_CANT_EXEC_CGI           0xC00009CFL

//
// MessageId: SSINCMSG_CANT_EXEC_ISA
//
// MessageText:
//
//  <B>Failed to execute ISAPI extension :  Win32 Error Code = %2!.20s!</B><BR>
//
#define SSINCMSG_CANT_EXEC_ISA           0xC00009D0L

//
// MessageId: SSINCMSG_NO_EXECUTE_PERMISSION
//
// MessageText:
//
//  <B>Cannot #EXEC file due to lack of EXECUTE permission</B><BR>
//
#define SSINCMSG_NO_EXECUTE_PERMISSION   0xC00009D1L

//
// MessageId: SSINCMSG_ACCESS_DENIED
//
// MessageText:
//
//  <B>Cannot process file due to access denied</B><BR>
//
#define SSINCMSG_ACCESS_DENIED           0xC00009D2L

//
// MessageId: SSINCMSG_MAX_NESTED_INCLUDES
//
// MessageText:
//
//  <B>A server side include file has included itself or the maximum depth of server side includes has been exceeded.</B><BR>
//
#define SSINCMSG_MAX_NESTED_INCLUDES     0xC00009D3L

//
// MessageId: SSINCMSG_CMD_NOT_ENABLED
//
// MessageText:
//
//  <B>The CMD option is not enabled for #EXEC calls</B><BR>
//
#define SSINCMSG_CMD_NOT_ENABLED         0xC00009D4L

//
// MessageId: SSINCMSG_EXEC_DISABLED
//
// MessageText:
//
//  <B>#EXEC calls have been disabled for this virtual path</B><BR>
//
#define SSINCMSG_EXEC_DISABLED           0xC00009D5L

//
// MessageId: SSINCMSG_ERROR_RECURSIVE_INCLUDE
//
// MessageText:
//
//  <B>There is a recursive #INCLUDE chain</B><BR>
//
#define SSINCMSG_ERROR_RECURSIVE_INCLUDE 0xC00009D6L

//
// MessageId: SSINCMSG_CANT_EXEC_CGI_REPORT_HTTP_STATUS
//
// MessageText:
//
//  <B>Failed to execute script:  Http Status Code = %2!.20s!</B><BR>
//
#define SSINCMSG_CANT_EXEC_CGI_REPORT_HTTP_STATUS 0xC00009D7L


#endif  // _SSINCMSG_H_

/**********************************************************************/
/**                       Microsoft Windows NT                       **/
/**                Copyright(c) Microsoft Corp., 1993                **/
/**********************************************************************/

/*
    odbcmsg.h

    This file is generated by the MC tool from the ODBCMSG.MC message
    file.


    FILE HISTORY:
        KeithMo     19-Mar-1993 Created.

*/


#ifndef _ODBCMSG_H_
#define _ODBCMSG_H_

//
// MessageId: ODBCMSG_MISSING_REQ_PARAM
//
// MessageText:
//
//  <p>
//  The form you just filled in requires the <b>%1</b> entry to be filled in. Please fill in that entry in the form and resubmit the form.
//  </p>
//
#define ODBCMSG_MISSING_REQ_PARAM        0xC0000A2AL

//
// MessageId: ODBCMSG_QUERY_FILE_NOT_FOUND
//
// MessageText:
//
//  <p>
//  The query file could not be opened. The file may not exist or you may have insufficient permission to open the file.
//  </p>
//
#define ODBCMSG_QUERY_FILE_NOT_FOUND     0xC0000A2BL

//
// MessageId: ODBCMSG_TOO_MANY_ELSES
//
// MessageText:
//
//  <p>
//  The template file contains an <i>else</i> tag without a matching <i>if</i> tag.
//  </p>
//
#define ODBCMSG_TOO_MANY_ELSES           0xC0000A2DL

//
// MessageId: ODBCMSG_TOO_MANY_ENDIFS
//
// MessageText:
//
//  <p>
//  The template file contains an <i>endif</i> tag without a matching <i>if</i> tag.
//  </p>
//
#define ODBCMSG_TOO_MANY_ENDIFS          0xC0000A2EL

//
// MessageId: ODBCMSG_MISMATCHED_VALUES
//
// MessageText:
//
//  <p>
//  The template file contains an expression with parameters that are of different type. For example, an <i>if</i> tag comparing a string with a number would cause this error.
//  </p>
//
#define ODBCMSG_MISMATCHED_VALUES        0xC0000A2FL

//
// MessageId: ODBCMSG_CONTAINS_ONLY_VALID_ON_STRINGS
//
// MessageText:
//
//  <p>
//  The template file contains an expression using the <i>CONTAINS</i> operator where one or both parameters are not strings. <i>CONTAINS</i> is only valid with string values.
//  </p>
//
#define ODBCMSG_CONTAINS_ONLY_VALID_ON_STRINGS 0xC0000A30L

//
// MessageId: ODBCMSG_UNBALANCED_STRING
//
// MessageText:
//
//  <p>
//  The template file contains an expression that uses a quoted string but the close quote is missing.
//  </p>
//
#define ODBCMSG_UNBALANCED_STRING        0xC0000A31L

//
// MessageId: ODBCMSG_UNRECOGNIZED_OPERATOR
//
// MessageText:
//
//  <p>
//  The template file contains an expression with an unrecognized operator. Valid operators are <i>GT</i>, <i>LT</i>, <i>EQ</i> and <i>CONTAINS</i>.
//  </p>
//
#define ODBCMSG_UNRECOGNIZED_OPERATOR    0xC0000A32L

//
// MessageId: ODBCMSG_UNREC_FIELD
//
// MessageText:
//
//  <p>
//  The query file contains an unrecognized field <b>%1</b>.
//  </p>
//
#define ODBCMSG_UNREC_FIELD              0xC0000A33L

//
// MessageId: ODBCMSG_DSN_AND_SQLSTATEMENT_REQ
//
// MessageText:
//
//  <p>
//  The query file must contain a valid, non-empty <i>Datasource:</i> field and <i>SQLStatement:</i> field.
//  </p>
//
#define ODBCMSG_DSN_AND_SQLSTATEMENT_REQ 0xC0000A34L

//
// MessageId: ODBCMSG_CANT_LOAD_ODBC
//
// MessageText:
//
//  Content-type: text/html
//  
//  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
//  <html dir=ltr>
//  <head>
//  <META NAME="ROBOTS" CONTENT="NOINDEX">
//  <title>The page cannot be displayed</title>
//  <META HTTP-EQUIV="Content-Type" Content="text/html; charset=Windows-1252">
//  </head>
//  <body>
//  <h1>
//  The library odbc32.dll could not be loaded to perform the query. Make sure ODBC has been properly installed on the server.
//  </h1>
//  </body>
//  </html>
//
#define ODBCMSG_CANT_LOAD_ODBC           0xC0000A35L

//
// MessageId: ODBCMSG_ERROR_PERFORMING_QUERY
//
// MessageText:
//
//  Content-type: text/html
//  
//  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
//  <html dir=ltr>
//  <head>
//  <META NAME="ROBOTS" CONTENT="NOINDEX">
//  <title>The page cannot be displayed</title>
//  <META HTTP-EQUIV="Content-Type" Content="text/html; charset=Windows-1252">
//  </head>
//  <body>
//  <h1>
//  Error performing query.
//  </h1>
//  %1
//  </body>
//  </html>
//
#define ODBCMSG_ERROR_PERFORMING_QUERY   0xC0000A37L

//
// MessageId: ODBCMSG_TOO_MANY_SQL_STATEMENTS
//
// MessageText:
//
//  <p>
//  The maximum number of SQLStatement fields in the IDC file has been exceeded.
//  </p>
//
#define ODBCMSG_TOO_MANY_SQL_STATEMENTS  0xC0000A38L


#endif // _ODBCMSG_H_

/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 1992-1996  Microsoft Corporation

Module Name:

    w3msg.h
       (generated from w3msg.mc)

Abstract:

   Event message definititions used by routines in the
   Internet Information Service Extensible Performance Counters

Created:

    24-Aug-00 Emily Kruglick

Revision History:

--*/
#ifndef _w3MSG_H_
#define _w3MSG_H_

//
//
//     ERRORS
//
//
// MessageId: W3_UNABLE_QUERY_W3SVC_DATA
//
// MessageText:
//
//  Unable to query the W3SVC (HTTP) service performance data.
//  The error code returned by the service is data DWORD 0.
//
#define W3_UNABLE_QUERY_W3SVC_DATA       ((DWORD)0xC00007D0L)

//
// MessageId: W3_W3SVC_REFRESH_TAKING_TOO_LONG
//
// MessageText:
//
//  It has taken too long to refresh the W3SVC counters, the stale counters are being used instead.
//
#define W3_W3SVC_REFRESH_TAKING_TOO_LONG ((DWORD)0xC00007D1L)

//
// MessageId: W3_W3SVC_REGISTRATION_MAY_BE_BAD
//
// MessageText:
//
//  Setting up Web Service counters failed, please make sure your Web Service counters are registered correctly.
//
#define W3_W3SVC_REGISTRATION_MAY_BE_BAD ((DWORD)0xC00007D2L)

//
// MessageId: W3_W3SVC_REFRESH_TAKING_TOO_LONG_STOPPING_LOGGING
//
// MessageText:
//
//  It has taken too long to refresh the W3SVC counters, the stale counters are being used instead.  This is the second message within the past %1 (hours, minutes, seconds).  No more stale counter messages will be logged for this client session until the time limit expires.
//  %nFor additional information specific to this message please visit the Microsoft Online Support site located at: http://go.microsoft.com/fwlink?linkid=538.
//
#define W3_W3SVC_REFRESH_TAKING_TOO_LONG_STOPPING_LOGGING ((DWORD)0xC00007D3L)

//
#endif //_w3MSG_H_
#if ! defined( MESSAGES_HEADER_FILE )

#define MESSAGES_HEADER_FILE

//
// MessageId: MSG_DENALI_ERROR_1
//
// MessageText:
//
//  Error: %1.
//
#define MSG_DENALI_ERROR_1               ((DWORD)0xC0000005L)

//
// MessageId: MSG_DENALI_ERROR_2
//
// MessageText:
//
//  Error: %1, %2.
//
#define MSG_DENALI_ERROR_2               ((DWORD)0xC0000006L)

//
// MessageId: MSG_DENALI_ERROR_3
//
// MessageText:
//
//  Error: %1, %2, %3.
//
#define MSG_DENALI_ERROR_3               ((DWORD)0xC0000007L)

//
// MessageId: MSG_DENALI_ERROR_4
//
// MessageText:
//
//  Error: %1, %2, %3, %4.
//
#define MSG_DENALI_ERROR_4               ((DWORD)0xC0000008L)

//
// MessageId: MSG_DENALI_WARNING_1
//
// MessageText:
//
//  Warning: %1.
//
#define MSG_DENALI_WARNING_1             ((DWORD)0x80000009L)

//
// MessageId: MSG_DENALI_WARNING_2
//
// MessageText:
//
//  Warning: %1, %2.
//
#define MSG_DENALI_WARNING_2             ((DWORD)0x80000010L)

//
// MessageId: MSG_DENALI_WARNING_3
//
// MessageText:
//
//  Warning: %1, %2, %3.
//
#define MSG_DENALI_WARNING_3             ((DWORD)0x80000011L)

//
// MessageId: MSG_DENALI_WARNING_4
//
// MessageText:
//
//  Warning: %1, %2, %3, %4.
//
#define MSG_DENALI_WARNING_4             ((DWORD)0x80000012L)

//
// MessageId: MSG_SWC_PARTITION_ACCESS_DENIED
//
// MessageText:
//
//  Failed to create an ASP Session due to Access Denied when activating COM+ Partition %1.
//
#define MSG_SWC_PARTITION_ACCESS_DENIED  ((DWORD)0xC0000013L)

//
// MessageId: MSG_SWC_INVALID_PARTITION_GUID
//
// MessageText:
//
//  Failed to create ASP Application %1 due to invalid or missing COM+ Partition ID.
//
#define MSG_SWC_INVALID_PARTITION_GUID   ((DWORD)0xC0000014L)

//
// MessageId: MSG_APPL_ERROR_GETTING_ANON_TOKEN
//
// MessageText:
//
//  Failed to retrieve the Anonymous User Token for ASP Application %1.  Global.ASA OnEnd routines will not be executed.
//
#define MSG_APPL_ERROR_GETTING_ANON_TOKEN ((DWORD)0xC0000015L)

//
// MessageId: MSG_APPL_ERROR_IMPERSONATING_ANON_USER
//
// MessageText:
//
//  Failed to impersonate the Anonymous User for ASP Application %1.  Global.ASA OnEnd routines will not be executed.
//
#define MSG_APPL_ERROR_IMPERSONATING_ANON_USER ((DWORD)0xC0000016L)

//
// MessageId: MSG_APPL_WARNING_DEFAULT_SCRIPTLANGUAGE
//
// MessageText:
//
//  No Default Script Language specified for Application %s.  Using default: %s.
//
#define MSG_APPL_WARNING_DEFAULT_SCRIPTLANGUAGE ((DWORD)0x80000017L)

//
// MessageId: MSG_CO_E_CLASSSTRING
//
// MessageText:
//
//  Invalid ProgID.
//
#define MSG_CO_E_CLASSSTRING             ((DWORD)0x800401F3L)


 #endif // MESSAGES_HEADER_FILE
/**********************************************************************/
/**                       Microsoft Windows NT                       **/
/**                Copyright(c) Microsoft Corp., 1993                **/
/**********************************************************************/

/*
    msg.h

    This file is generated by the MC tool from the MSG.MC message
    file.


    FILE HISTORY:
        KeithMo     19-Mar-1993 Created.

*/


#ifndef _MSG_H_
#define _MSG_H_

//
// MessageId: FTPD_EVENT_CANNOT_INITIALIZE_SECURITY
//
// MessageText:
//
//  FTP Server could not initialize its security.  The data is the error.
//
#define FTPD_EVENT_CANNOT_INITIALIZE_SECURITY ((DWORD)0xC0040001L)

//
// MessageId: FTPD_EVENT_CANNOT_INITIALIZE_WINSOCK
//
// MessageText:
//
//  FTP Server could not initialize the socket library.  The data is the error.
//
#define FTPD_EVENT_CANNOT_INITIALIZE_WINSOCK ((DWORD)0xC0040003L)

//
// MessageId: FTPD_EVENT_OUT_OF_MEMORY
//
// MessageText:
//
//  FTP Server was unable to initialize due to a shortage of available memory.  The data is the error.
//
#define FTPD_EVENT_OUT_OF_MEMORY         ((DWORD)0xC0040004L)

//
// MessageId: FTPD_EVENT_CANNOT_LOCATE_FTP
//
// MessageText:
//
//  FTP Server could not locate the FTP/TCP service.  The data is the error.
//
#define FTPD_EVENT_CANNOT_LOCATE_FTP     ((DWORD)0xC0040005L)

//
// MessageId: FTPD_EVENT_CANNOT_CREATE_CONNECTION_SOCKET
//
// MessageText:
//
//  FTP Server could not create the main connection socket.  The data is the error.
//
#define FTPD_EVENT_CANNOT_CREATE_CONNECTION_SOCKET ((DWORD)0xC0040006L)

//
// MessageId: FTPD_EVENT_CANNOT_CREATE_CONNECTION_THREAD
//
// MessageText:
//
//  FTP Server could not create the main connection thread.  The data is the error.
//
#define FTPD_EVENT_CANNOT_CREATE_CONNECTION_THREAD ((DWORD)0xC0040007L)

//
// MessageId: FTPD_EVENT_CANNOT_CREATE_CLIENT_THREAD
//
// MessageText:
//
//  FTP Server could not create a client worker thread for user at host %1.  The connection to this user is terminated.  The data is the error.
//
#define FTPD_EVENT_CANNOT_CREATE_CLIENT_THREAD ((DWORD)0xC0040008L)

//
// MessageId: FTPD_EVENT_SYSTEM_CALL_FAILED
//
// MessageText:
//
//  A call to a system service failed unexpectedly.  The data is the error.
//
#define FTPD_EVENT_SYSTEM_CALL_FAILED    ((DWORD)0xC0040009L)

//
// MessageId: FTPD_EVENT_CLIENT_TIMEOUT
//
// MessageText:
//
//  User %1 at host %2 has timed-out after %3 seconds of inactivity.
//
#define FTPD_EVENT_CLIENT_TIMEOUT        ((DWORD)0x8004000AL)

//
// MessageId: FTPD_EVENT_ANONYMOUS_LOGON
//
// MessageText:
//
//  Anonymous logon request received from %1 at host %2.
//
#define FTPD_EVENT_ANONYMOUS_LOGON       ((DWORD)0x4004000BL)

//
// MessageId: FTPD_EVENT_NONANONYMOUS_LOGON
//
// MessageText:
//
//  User logon request received from %1 at host %2.
//
#define FTPD_EVENT_NONANONYMOUS_LOGON    ((DWORD)0x4004000CL)

//
// MessageId: FTPD_EVENT_BAD_HOME_DIRECTORY
//
// MessageText:
//
//  User %1 failed to log on, could not access the home directory %2.
//
#define FTPD_EVENT_BAD_HOME_DIRECTORY    ((DWORD)0x8004000DL)

//
// MessageId: FTPD_EVENT_RETRO_ACCESS_DENIED
//
// MessageText:
//
//  User %1 denied access to the current directory %2 due to a security change.
//
#define FTPD_EVENT_RETRO_ACCESS_DENIED   ((DWORD)0x8004000EL)

//
// MessageId: FTP_PASVPORT_MB_ACCESS_FAILED
//
// MessageText:
//
//  Failed to read metabase property PassivePortRange under the FTP Service node %1.
//
#define FTP_PASVPORT_MB_ACCESS_FAILED    ((DWORD)0xC004000FL)

//
// MessageId: FTP_PASVPORT_INVALID_VALUE
//
// MessageText:
//
//  The FTP Service configuration property PassivePortRange has invalid value: %1.
//
#define FTP_PASVPORT_INVALID_VALUE       ((DWORD)0xC0040010L)


#endif  // _MSG_H_

