386_OBJECTS= \
    $(_OBJ_DIR)\i386\certlog.res \
    $(_OBJ_DIR)\i386\certlog.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\certlog.res \
    $(_OBJ_DIR)\ia64\certlog.obj

PASS0_IA64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\certlog.res \
    $(_OBJ_DIR)\amd64\certlog.obj

PASS0_AMD64_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\certlog.res \
    $(_OBJ_DIR)\arm\certlog.obj

PASS0_ARM_OBJECTS=

