386_OBJECTS= \
    $(_OBJ_DIR)\i386\guids.obj

PASS0_386_OBJECTS= \
    $(PASS0_HEADERDIR)\daxpress.h

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\guids.obj

PASS0_IA64_OBJECTS= \
    $(PASS0_HEADERDIR)\daxpress.h

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\guids.obj

PASS0_AMD64_OBJECTS= \
    $(PASS0_HEADERDIR)\daxpress.h

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\guids.obj

PASS0_ARM_OBJECTS= \
    $(PASS0_HEADERDIR)\daxpress.h

