386_OBJECTS= \
    $(_OBJ_DIR)\i386\padguids.obj

PASS0_386_OBJECTS= \
    $(PASS0_HEADERDIR)\imepadsv.h

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\padguids.obj

PASS0_IA64_OBJECTS= \
    $(PASS0_HEADERDIR)\imepadsv.h

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\padguids.obj

PASS0_AMD64_OBJECTS= \
    $(PASS0_HEADERDIR)\imepadsv.h

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\padguids.obj

PASS0_ARM_OBJECTS= \
    $(PASS0_HEADERDIR)\imepadsv.h

