
#ifdef MINIMAL_FUNCTIONALITY
#else

#include "jet.h"

#include <cstring>
#include <algorithm>

using namespace std;

struct ERROR
	{
	JET_ERR      err;
	const char * szError;
	const char * szErrorText;
	};

class FIND_ERRNUM
	{
	public:
		FIND_ERRNUM( JET_ERR err ) : m_err( err ) {}
		bool operator()( const ERROR& error ) { return m_err == error.err; }

	private:
		const JET_ERR m_err;
	};

class FIND_ERRSTR
	{
	public:
		FIND_ERRSTR( const char * szErr ) : m_szErr( szErr ) {}
		bool operator()( const ERROR& error ) { return !_stricmp( m_szErr, error.szError ); }

	private:
		const char * const m_szErr;
	};
	
static char szUnknownError[] = "Unknown Error";

static const ERROR rgerror[] = {
	{ JET_errSuccess,	"JET_errSuccess",	"Successful Operation" },
	{ JET_wrnNyi,	"JET_wrnNyi",	"Function Not Yet Implemented" },
	{ JET_errRfsFailure,	"JET_errRfsFailure",	"Resource Failure Simulator failure" },
	{ JET_errRfsNotArmed,	"JET_errRfsNotArmed",	"Resource Failure Simulator not initialized" },
	{ JET_errFileClose,	"JET_errFileClose",	"Could not close file" },
	{ JET_errOutOfThreads,	"JET_errOutOfThreads",	"Could not start thread" },
	{ JET_errTooManyIO,	"JET_errTooManyIO",	"System busy due to too many IOs" },
	{ JET_errTaskDropped,	"JET_errTaskDropped",	"A requested async task could not be executed" },
	{ JET_errInternalError,	"JET_errInternalError",	"Fatal internal error" },
	{ JET_errDatabaseBufferDependenciesCorrupted,	"JET_errDatabaseBufferDependenciesCorrupted",	"Buffer dependencies improperly set. Recovery failure" },
	{ JET_wrnRemainingVersions,	"JET_wrnRemainingVersions",	"The version store is still active" },
	{ JET_errPreviousVersion,	"JET_errPreviousVersion",	"Version already existed. Recovery failure" },
	{ JET_errPageBoundary,	"JET_errPageBoundary",	"Reached Page Boundary" },
	{ JET_errKeyBoundary,	"JET_errKeyBoundary",	"Reached Key Boundary" },
	{ JET_errBadPageLink,	"JET_errBadPageLink",	"Database corrupted" },
	{ JET_errBadBookmark,	"JET_errBadBookmark",	"Bookmark has no corresponding address in database" },
	{ JET_errNTSystemCallFailed,	"JET_errNTSystemCallFailed",	"A call to the operating system failed" },
	{ JET_errBadParentPageLink,	"JET_errBadParentPageLink",	"Database corrupted" },
	{ JET_errSPAvailExtCacheOutOfSync,	"JET_errSPAvailExtCacheOutOfSync",	"AvailExt cache doesn't match btree" },
	{ JET_errSPAvailExtCorrupted,	"JET_errSPAvailExtCorrupted",	"AvailExt space tree is corrupt" },
	{ JET_errSPAvailExtCacheOutOfMemory,	"JET_errSPAvailExtCacheOutOfMemory",	"Out of memory allocating an AvailExt cache node" },
	{ JET_errSPOwnExtCorrupted,	"JET_errSPOwnExtCorrupted",	"OwnExt space tree is corrupt" },
	{ JET_errDbTimeCorrupted,	"JET_errDbTimeCorrupted",	"Dbtime on current page is greater than global database dbtime" },
	{ JET_wrnUniqueKey,	"JET_wrnUniqueKey",	"seek on non-unique index yielded a unique key" },
	{ JET_wrnSeparateLongValue,	"JET_wrnSeparateLongValue",	"Column is a separated long-value" },
	{ JET_errKeyTooBig,	"JET_errKeyTooBig",	"Key is too large" },
	{ JET_errInvalidLoggedOperation,	"JET_errInvalidLoggedOperation",	"Logged operation cannot be redone" },
	{ JET_errLogFileCorrupt,	"JET_errLogFileCorrupt",	"Log file is corrupt" },
	{ JET_errNoBackupDirectory,	"JET_errNoBackupDirectory",	"No backup directory given" },
	{ JET_errBackupDirectoryNotEmpty,	"JET_errBackupDirectoryNotEmpty",	"The backup directory is not emtpy" },
	{ JET_errBackupInProgress,	"JET_errBackupInProgress",	"Backup is active already" },
	{ JET_errRestoreInProgress,	"JET_errRestoreInProgress",	"Restore in progress" },
	{ JET_errMissingPreviousLogFile,	"JET_errMissingPreviousLogFile",	"Missing the log file for check point" },
	{ JET_errLogWriteFail,	"JET_errLogWriteFail",	"Failure writing to log file" },
	{ JET_errLogDisabledDueToRecoveryFailure,	"JET_errLogDisabledDueToRecoveryFailure",	"Try to log something after recovery faild" },
	{ JET_errCannotLogDuringRecoveryRedo,	"JET_errCannotLogDuringRecoveryRedo",	"Try to log something during recovery redo" },
	{ JET_errLogGenerationMismatch,	"JET_errLogGenerationMismatch",	"Name of logfile does not match internal generation number" },
	{ JET_errBadLogVersion,	"JET_errBadLogVersion",	"Version of log file is not compatible with Jet version" },
	{ JET_errInvalidLogSequence,	"JET_errInvalidLogSequence",	"Timestamp in next log does not match expected" },
	{ JET_errLoggingDisabled,	"JET_errLoggingDisabled",	"Log is not active" },
	{ JET_errLogBufferTooSmall,	"JET_errLogBufferTooSmall",	"Log buffer is too small for recovery" },
	{ JET_errLogSequenceEnd,	"JET_errLogSequenceEnd",	"Maximum log file number exceeded" },
	{ JET_errNoBackup,	"JET_errNoBackup",	"No backup in progress" },
	{ JET_errInvalidBackupSequence,	"JET_errInvalidBackupSequence",	"Backup call out of sequence" },
	{ JET_errBackupNotAllowedYet,	"JET_errBackupNotAllowedYet",	"Cannot do backup now" },
	{ JET_errDeleteBackupFileFail,	"JET_errDeleteBackupFileFail",	"Could not delete backup file" },
	{ JET_errMakeBackupDirectoryFail,	"JET_errMakeBackupDirectoryFail",	"Could not make backup temp directory" },
	{ JET_errInvalidBackup,	"JET_errInvalidBackup",	"Cannot perform incremental backup when circular logging enabled" },
	{ JET_errRecoveredWithErrors,	"JET_errRecoveredWithErrors",	"Restored with errors" },
	{ JET_errMissingLogFile,	"JET_errMissingLogFile",	"Current log file missing" },
	{ JET_errLogDiskFull,	"JET_errLogDiskFull",	"Log disk full" },
	{ JET_errBadLogSignature,	"JET_errBadLogSignature",	"Bad signature for a log file" },
	{ JET_errBadDbSignature,	"JET_errBadDbSignature",	"Bad signature for a db file" },
	{ JET_errBadCheckpointSignature,	"JET_errBadCheckpointSignature",	"Bad signature for a checkpoint file" },
	{ JET_errCheckpointCorrupt,	"JET_errCheckpointCorrupt",	"Checkpoint file not found or corrupt" },
	{ JET_errMissingPatchPage,	"JET_errMissingPatchPage",	"Patch file page not found during recovery" },
	{ JET_errBadPatchPage,	"JET_errBadPatchPage",	"Patch file page is not valid" },
	{ JET_errRedoAbruptEnded,	"JET_errRedoAbruptEnded",	"Redo abruptly ended due to sudden failure in reading logs from log file" },
	{ JET_errBadSLVSignature,	"JET_errBadSLVSignature",	"Signature in SLV file does not agree with database" },
	{ JET_errPatchFileMissing,	"JET_errPatchFileMissing",	"Hard restore detected that patch file is missing from backup set" },
	{ JET_errDatabaseLogSetMismatch,	"JET_errDatabaseLogSetMismatch",	"Database does not belong with the current set of log files" },
	{ JET_errDatabaseStreamingFileMismatch,	"JET_errDatabaseStreamingFileMismatch",	"Database and streaming file do not match each other" },
	{ JET_errLogFileSizeMismatch,	"JET_errLogFileSizeMismatch",	"actual log file size does not match JET_paramLogFileSize" },
	{ JET_errCheckpointFileNotFound,	"JET_errCheckpointFileNotFound",	"Could not locate checkpoint file" },
	{ JET_errRequiredLogFilesMissing,	"JET_errRequiredLogFilesMissing",	"The required log files for recovery is missing." },
	{ JET_errSoftRecoveryOnBackupDatabase,	"JET_errSoftRecoveryOnBackupDatabase",	"Soft recovery is intended on a backup database. Restore should be used instead" },
	{ JET_errLogFileSizeMismatchDatabasesConsistent,	"JET_errLogFileSizeMismatchDatabasesConsistent",	"databases have been recovered, but the log file size used during recovery does not match JET_paramLogFileSize" },
	{ JET_errLogSectorSizeMismatch,	"JET_errLogSectorSizeMismatch",	"the log file sector size does not match the current volume's sector size" },
	{ JET_errLogSectorSizeMismatchDatabasesConsistent,	"JET_errLogSectorSizeMismatchDatabasesConsistent",	"databases have been recovered, but the log file sector size (used during recovery) does not match the current volume's sector size" },
	{ JET_errLogSequenceEndDatabasesConsistent,	"JET_errLogSequenceEndDatabasesConsistent",	"databases have been recovered, but all possible log generations in the current sequence are used; delete all log files and the checkpoint file and backup the databases before continuing" },
	{ JET_errStreamingDataNotLogged,	"JET_errStreamingDataNotLogged",	"Illegal attempt to replay a streaming file operation where the data wasn't logged. Probably caused by an attempt to roll-forward with circular logging enabled" },
	{ JET_errDatabaseDirtyShutdown,	"JET_errDatabaseDirtyShutdown",	"Database was not shutdown cleanly. Recovery must first be run to properly complete database operations for the previous shutdown." },
	{ JET_errConsistentTimeMismatch,	"JET_errConsistentTimeMismatch",	"Database last consistent time unmatched" },
	{ JET_errDatabasePatchFileMismatch,	"JET_errDatabasePatchFileMismatch",	"Patch file is not generated from this backup" },
	{ JET_errEndingRestoreLogTooLow,	"JET_errEndingRestoreLogTooLow",	"The starting log number too low for the restore" },
	{ JET_errStartingRestoreLogTooHigh,	"JET_errStartingRestoreLogTooHigh",	"The starting log number too high for the restore" },
	{ JET_errGivenLogFileHasBadSignature,	"JET_errGivenLogFileHasBadSignature",	"Restore log file has bad signature" },
	{ JET_errGivenLogFileIsNotContiguous,	"JET_errGivenLogFileIsNotContiguous",	"Restore log file is not contiguous" },
	{ JET_errMissingRestoreLogFiles,	"JET_errMissingRestoreLogFiles",	"Some restore log files are missing" },
	{ JET_wrnExistingLogFileHasBadSignature,	"JET_wrnExistingLogFileHasBadSignature",	"Existing log file has bad signature" },
	{ JET_wrnExistingLogFileIsNotContiguous,	"JET_wrnExistingLogFileIsNotContiguous",	"Existing log file is not contiguous" },
	{ JET_errMissingFullBackup,	"JET_errMissingFullBackup",	"The database miss a previous full backup befor incremental backup" },
	{ JET_errBadBackupDatabaseSize,	"JET_errBadBackupDatabaseSize",	"The backup database size is not in 4k" },
	{ JET_errDatabaseAlreadyUpgraded,	"JET_errDatabaseAlreadyUpgraded",	"Attempted to upgrade a database that is already current" },
	{ JET_errDatabaseIncompleteUpgrade,	"JET_errDatabaseIncompleteUpgrade",	"Attempted to use a database which was only partially converted to the current format -- must restore from backup" },
	{ JET_wrnSkipThisRecord,	"JET_wrnSkipThisRecord",	"INTERNAL ERROR" },
	{ JET_errMissingCurrentLogFiles,	"JET_errMissingCurrentLogFiles",	"Some current log files are missing for continous restore" },
	{ JET_errDbTimeTooOld,	"JET_errDbTimeTooOld",	"dbtime on page smaller than dbtimeBefore in record" },
	{ JET_errDbTimeTooNew,	"JET_errDbTimeTooNew",	"dbtime on page in advence of the dbtimeBefore in record" },
	{ JET_errMissingFileToBackup,	"JET_errMissingFileToBackup",	"Some log or patch files are missing during backup" },
	{ JET_errLogTornWriteDuringHardRestore,	"JET_errLogTornWriteDuringHardRestore",	"torn-write was detected in a backup set during hard restore" },
	{ JET_errLogTornWriteDuringHardRecovery,	"JET_errLogTornWriteDuringHardRecovery",	"torn-write was detected during hard recovery (log was not part of a backup set)" },
	{ JET_errLogCorruptDuringHardRestore,	"JET_errLogCorruptDuringHardRestore",	"corruption was detected in a backup set during hard restore" },
	{ JET_errLogCorruptDuringHardRecovery,	"JET_errLogCorruptDuringHardRecovery",	"corruption was detected during hard recovery (log was not part of a backup set)" },
	{ JET_errMustDisableLoggingForDbUpgrade,	"JET_errMustDisableLoggingForDbUpgrade",	"Cannot have logging enabled while attempting to upgrade db" },
	{ JET_errBadRestoreTargetInstance,	"JET_errBadRestoreTargetInstance",	"TargetInstance specified for restore is not found or log files don't match" },
	{ JET_wrnTargetInstanceRunning,	"JET_wrnTargetInstanceRunning",	"TargetInstance specified for restore is running" },
	{ JET_errDatabasesNotFromSameSnapshot,	"JET_errDatabasesNotFromSameSnapshot",	"Databases to be restored are not from the same shadow copy backup" },
	{ JET_errSoftRecoveryOnSnapshot,	"JET_errSoftRecoveryOnSnapshot",	"Soft recovery on a database from a shadow copy backup set" },
	{ JET_wrnDatabaseRepaired,	"JET_wrnDatabaseRepaired",	"Database corruption has been repaired" },
	{ JET_errUnicodeTranslationBufferTooSmall,	"JET_errUnicodeTranslationBufferTooSmall",	"Unicode translation buffer too small" },
	{ JET_errUnicodeTranslationFail,	"JET_errUnicodeTranslationFail",	"Unicode normalization failed" },
	{ JET_errUnicodeNormalizationNotSupported,	"JET_errUnicodeNormalizationNotSupported",	"OS does not provide support for Unicode normalisation (and no normalisation callback was specified)" },
	{ JET_errExistingLogFileHasBadSignature,	"JET_errExistingLogFileHasBadSignature",	"Existing log file has bad signature" },
	{ JET_errExistingLogFileIsNotContiguous,	"JET_errExistingLogFileIsNotContiguous",	"Existing log file is not contiguous" },
	{ JET_errLogReadVerifyFailure,	"JET_errLogReadVerifyFailure",	"Checksum error in log file during backup" },
	{ JET_errSLVReadVerifyFailure,	"JET_errSLVReadVerifyFailure",	"Checksum error in SLV file during backup" },
	{ JET_errCheckpointDepthTooDeep,	"JET_errCheckpointDepthTooDeep",	"too many outstanding generations between checkpoint and current generation" },
	{ JET_errRestoreOfNonBackupDatabase,	"JET_errRestoreOfNonBackupDatabase",	"hard recovery attempted on a database that wasn't a backup database" },
	{ JET_errBackupAbortByServer,	"JET_errBackupAbortByServer",	"Backup was aborted by server by calling JetTerm with JET_bitTermStopBackup or by calling JetStopBackup" },
	{ JET_errInvalidGrbit,	"JET_errInvalidGrbit",	"Invalid parameter" },
	{ JET_errTermInProgress,	"JET_errTermInProgress",	"Termination in progress" },
	{ JET_errFeatureNotAvailable,	"JET_errFeatureNotAvailable",	"API not supported" },
	{ JET_errInvalidName,	"JET_errInvalidName",	"Invalid name" },
	{ JET_errInvalidParameter,	"JET_errInvalidParameter",	"Invalid API parameter" },
	{ JET_wrnColumnNull,	"JET_wrnColumnNull",	"Column is NULL-valued" },
	{ JET_wrnBufferTruncated,	"JET_wrnBufferTruncated",	"Buffer too small for data" },
	{ JET_wrnDatabaseAttached,	"JET_wrnDatabaseAttached",	"Database is already attached" },
	{ JET_errDatabaseFileReadOnly,	"JET_errDatabaseFileReadOnly",	"Tried to attach a read-only database file for read/write operations" },
	{ JET_wrnSortOverflow,	"JET_wrnSortOverflow",	"Sort does not fit in memory" },
	{ JET_errInvalidDatabaseId,	"JET_errInvalidDatabaseId",	"Invalid database id" },
	{ JET_errOutOfMemory,	"JET_errOutOfMemory",	"Out of Memory" },
	{ JET_errOutOfDatabaseSpace,	"JET_errOutOfDatabaseSpace",	"Maximum database size reached" },
	{ JET_errOutOfCursors,	"JET_errOutOfCursors",	"Out of table cursors" },
	{ JET_errOutOfBuffers,	"JET_errOutOfBuffers",	"Out of database page buffers" },
	{ JET_errTooManyIndexes,	"JET_errTooManyIndexes",	"Too many indexes" },
	{ JET_errTooManyKeys,	"JET_errTooManyKeys",	"Too many columns in an index" },
	{ JET_errRecordDeleted,	"JET_errRecordDeleted",	"Record has been deleted" },
	{ JET_errReadVerifyFailure,	"JET_errReadVerifyFailure",	"Checksum error on a database page" },
	{ JET_errPageNotInitialized,	"JET_errPageNotInitialized",	"Blank database page" },
	{ JET_errOutOfFileHandles,	"JET_errOutOfFileHandles",	"Out of file handles" },
	{ JET_errDiskIO,	"JET_errDiskIO",	"Disk IO error" },
	{ JET_errInvalidPath,	"JET_errInvalidPath",	"Invalid file path" },
	{ JET_errInvalidSystemPath,	"JET_errInvalidSystemPath",	"Invalid system path" },
	{ JET_errInvalidLogDirectory,	"JET_errInvalidLogDirectory",	"Invalid log directory" },
	{ JET_errRecordTooBig,	"JET_errRecordTooBig",	"Record larger than maximum size" },
	{ JET_errTooManyOpenDatabases,	"JET_errTooManyOpenDatabases",	"Too many open databases" },
	{ JET_errInvalidDatabase,	"JET_errInvalidDatabase",	"Not a database file" },
	{ JET_errNotInitialized,	"JET_errNotInitialized",	"Database engine not initialized" },
	{ JET_errAlreadyInitialized,	"JET_errAlreadyInitialized",	"Database engine already initialized" },
	{ JET_errInitInProgress,	"JET_errInitInProgress",	"Database engine is being initialized" },
	{ JET_errFileAccessDenied,	"JET_errFileAccessDenied",	"Cannot access file, the file is locked or in use" },
	{ JET_errQueryNotSupported,	"JET_errQueryNotSupported",	"Query support unavailable" },
	{ JET_errSQLLinkNotSupported,	"JET_errSQLLinkNotSupported",	"SQL Link support unavailable" },
	{ JET_errBufferTooSmall,	"JET_errBufferTooSmall",	"Buffer is too small" },
	{ JET_wrnSeekNotEqual,	"JET_wrnSeekNotEqual",	"Exact match not found during seek" },
	{ JET_errTooManyColumns,	"JET_errTooManyColumns",	"Too many columns defined" },
	{ JET_errContainerNotEmpty,	"JET_errContainerNotEmpty",	"Container is not empty" },
	{ JET_errInvalidFilename,	"JET_errInvalidFilename",	"Filename is invalid" },
	{ JET_errInvalidBookmark,	"JET_errInvalidBookmark",	"Invalid bookmark" },
	{ JET_errColumnInUse,	"JET_errColumnInUse",	"Column used in an index" },
	{ JET_errInvalidBufferSize,	"JET_errInvalidBufferSize",	"Data buffer doesn't match column size" },
	{ JET_errColumnNotUpdatable,	"JET_errColumnNotUpdatable",	"Cannot set column value" },
	{ JET_errIndexInUse,	"JET_errIndexInUse",	"Index is in use" },
	{ JET_errLinkNotSupported,	"JET_errLinkNotSupported",	"Link support unavailable" },
	{ JET_errNullKeyDisallowed,	"JET_errNullKeyDisallowed",	"Null keys are disallowed on index" },
	{ JET_errNotInTransaction,	"JET_errNotInTransaction",	"Operation must be within a transaction" },
	{ JET_wrnNoErrorInfo,	"JET_wrnNoErrorInfo",	"No extended error information" },
	{ JET_wrnNoIdleActivity,	"JET_wrnNoIdleActivity",	"No idle activity occured" },
	{ JET_errTooManyActiveUsers,	"JET_errTooManyActiveUsers",	"Too many active database users" },
	{ JET_errInvalidCountry,	"JET_errInvalidCountry",	"Invalid or unknown country code" },
	{ JET_errInvalidLanguageId,	"JET_errInvalidLanguageId",	"Invalid or unknown language id" },
	{ JET_errInvalidCodePage,	"JET_errInvalidCodePage",	"Invalid or unknown code page" },
	{ JET_errInvalidLCMapStringFlags,	"JET_errInvalidLCMapStringFlags",	"Invalid flags for LCMapString()" },
	{ JET_errVersionStoreEntryTooBig,	"JET_errVersionStoreEntryTooBig",	"Attempted to create a version store entry (RCE) larger than a version bucket" },
	{ JET_errVersionStoreOutOfMemoryAndCleanupTimedOut,	"JET_errVersionStoreOutOfMemoryAndCleanupTimedOut",	"Version store out of memory (and cleanup attempt failed to complete)" },
	{ JET_wrnNoWriteLock,	"JET_wrnNoWriteLock",	"No write lock at transaction level 0" },
	{ JET_wrnColumnSetNull,	"JET_wrnColumnSetNull",	"Column set to NULL-value" },
	{ JET_errVersionStoreOutOfMemory,	"JET_errVersionStoreOutOfMemory",	"Version store out of memory (cleanup already attempted)" },
	{ JET_errCurrencyStackOutOfMemory,	"JET_errCurrencyStackOutOfMemory",	"UNUSED: lCSRPerfFUCB * g_lCursorsMax exceeded (XJET only)" },
	{ JET_errCannotIndex,	"JET_errCannotIndex",	"Cannot index escrow column or SLV column" },
	{ JET_errRecordNotDeleted,	"JET_errRecordNotDeleted",	"Record has not been deleted" },
	{ JET_errTooManyMempoolEntries,	"JET_errTooManyMempoolEntries",	"Too many mempool entries requested" },
	{ JET_errOutOfObjectIDs,	"JET_errOutOfObjectIDs",	"Out of btree ObjectIDs (perform offline defrag to reclaim freed/unused ObjectIds)" },
	{ JET_errOutOfLongValueIDs,	"JET_errOutOfLongValueIDs",	"Long-value ID counter has reached maximum value. (perform offline defrag to reclaim free/unused LongValueIDs)" },
	{ JET_errOutOfAutoincrementValues,	"JET_errOutOfAutoincrementValues",	"Auto-increment counter has reached maximum value (offline defrag WILL NOT be able to reclaim free/unused Auto-increment values)." },
	{ JET_errOutOfDbtimeValues,	"JET_errOutOfDbtimeValues",	"Dbtime counter has reached maximum value (perform offline defrag to reclaim free/unused Dbtime values)" },
	{ JET_errOutOfSequentialIndexValues,	"JET_errOutOfSequentialIndexValues",	"Sequential index counter has reached maximum value (perform offline defrag to reclaim free/unused SequentialIndex values)" },
	{ JET_errRunningInOneInstanceMode,	"JET_errRunningInOneInstanceMode",	"Multi-instance call with single-instance mode enabled" },
	{ JET_errRunningInMultiInstanceMode,	"JET_errRunningInMultiInstanceMode",	"Single-instance call with multi-instance mode enabled" },
	{ JET_errSystemParamsAlreadySet,	"JET_errSystemParamsAlreadySet",	"Global system parameters have already been set" },
	{ JET_errSystemPathInUse,	"JET_errSystemPathInUse",	"System path already used by another database instance" },
	{ JET_errLogFilePathInUse,	"JET_errLogFilePathInUse",	"Logfile path already used by another database instance" },
	{ JET_errTempPathInUse,	"JET_errTempPathInUse",	"Temp path already used by another database instance" },
	{ JET_errInstanceNameInUse,	"JET_errInstanceNameInUse",	"Instance Name already in use" },
	{ JET_errInstanceUnavailable,	"JET_errInstanceUnavailable",	"This instance cannot be used because it encountered a fatal error" },
	{ JET_errDatabaseUnavailable,	"JET_errDatabaseUnavailable",	"This database cannot be used because it encountered a fatal error" },
	{ JET_errInstanceUnavailableDueToFatalLogDiskFull,	"JET_errInstanceUnavailableDueToFatalLogDiskFull",	"This instance cannot be used because it encountered a log-disk-full error performing an operation (likely transaction rollback) that could not tolerate failure" },
	{ JET_errOutOfSessions,	"JET_errOutOfSessions",	"Out of sessions" },
	{ JET_errWriteConflict,	"JET_errWriteConflict",	"Write lock failed due to outstanding write lock" },
	{ JET_errTransTooDeep,	"JET_errTransTooDeep",	"Transactions nested too deeply" },
	{ JET_errInvalidSesid,	"JET_errInvalidSesid",	"Invalid session handle" },
	{ JET_errWriteConflictPrimaryIndex,	"JET_errWriteConflictPrimaryIndex",	"Update attempted on uncommitted primary index" },
	{ JET_errInTransaction,	"JET_errInTransaction",	"Operation not allowed within a transaction" },
	{ JET_errRollbackRequired,	"JET_errRollbackRequired",	"Must rollback current transaction -- cannot commit or begin a new one" },
	{ JET_errTransReadOnly,	"JET_errTransReadOnly",	"Read-only transaction tried to modify the database" },
	{ JET_errSessionWriteConflict,	"JET_errSessionWriteConflict",	"Attempt to replace the same record by two diffrerent cursors in the same session" },
	{ JET_errRecordTooBigForBackwardCompatibility,	"JET_errRecordTooBigForBackwardCompatibility",	"record would be too big if represented in a database format from a previous version of Jet" },
	{ JET_errCannotMaterializeForwardOnlySort,	"JET_errCannotMaterializeForwardOnlySort",	"The temp table could not be created due to parameters that conflict with JET_bitTTForwardOnly" },
	{ JET_errMustCommitDistributedTransactionToLevel0,	"JET_errMustCommitDistributedTransactionToLevel0",	"Attempted to PrepareToCommit a distributed transaction to non-zero level" },
	{ JET_errDistributedTransactionAlreadyPreparedToCommit,	"JET_errDistributedTransactionAlreadyPreparedToCommit",	"Attempted a write-operation after a distributed transaction has called PrepareToCommit" },
	{ JET_errNotInDistributedTransaction,	"JET_errNotInDistributedTransaction",	"Attempted to PrepareToCommit a non-distributed transaction" },
	{ JET_errDistributedTransactionNotYetPreparedToCommit,	"JET_errDistributedTransactionNotYetPreparedToCommit",	"Attempted to commit a distributed transaction, but PrepareToCommit has not yet been called" },
	{ JET_errCannotNestDistributedTransactions,	"JET_errCannotNestDistributedTransactions",	"Attempted to begin a distributed transaction when not at level 0" },
	{ JET_errDTCMissingCallback,	"JET_errDTCMissingCallback",	"Attempted to begin a distributed transaction but no callback for DTC coordination was specified on initialisation" },
	{ JET_errDTCMissingCallbackOnRecovery,	"JET_errDTCMissingCallbackOnRecovery",	"Attempted to recover a distributed transaction but no callback for DTC coordination was specified on initialisation" },
	{ JET_errDTCCallbackUnexpectedError,	"JET_errDTCCallbackUnexpectedError",	"Unexpected error code returned from DTC callback" },
	{ JET_wrnDTCCommitTransaction,	"JET_wrnDTCCommitTransaction",	"Warning code DTC callback should return if the specified transaction is to be committed" },
	{ JET_wrnDTCRollbackTransaction,	"JET_wrnDTCRollbackTransaction",	"Warning code DTC callback should return if the specified transaction is to be rolled back" },
	{ JET_errDatabaseDuplicate,	"JET_errDatabaseDuplicate",	"Database already exists" },
	{ JET_errDatabaseInUse,	"JET_errDatabaseInUse",	"Database in use" },
	{ JET_errDatabaseNotFound,	"JET_errDatabaseNotFound",	"No such database" },
	{ JET_errDatabaseInvalidName,	"JET_errDatabaseInvalidName",	"Invalid database name" },
	{ JET_errDatabaseInvalidPages,	"JET_errDatabaseInvalidPages",	"Invalid number of pages" },
	{ JET_errDatabaseCorrupted,	"JET_errDatabaseCorrupted",	"Non database file or corrupted db" },
	{ JET_errDatabaseLocked,	"JET_errDatabaseLocked",	"Database exclusively locked" },
	{ JET_errCannotDisableVersioning,	"JET_errCannotDisableVersioning",	"Cannot disable versioning for this database" },
	{ JET_errInvalidDatabaseVersion,	"JET_errInvalidDatabaseVersion",	"Database engine is incompatible with database" },
	{ JET_errDatabase200Format,	"JET_errDatabase200Format",	"The database is in an older (200) format" },
	{ JET_errDatabase400Format,	"JET_errDatabase400Format",	"The database is in an older (400) format" },
	{ JET_errDatabase500Format,	"JET_errDatabase500Format",	"The database is in an older (500) format" },
	{ JET_errPageSizeMismatch,	"JET_errPageSizeMismatch",	"The database page size does not match the engine" },
	{ JET_errTooManyInstances,	"JET_errTooManyInstances",	"Cannot start any more database instances" },
	{ JET_errDatabaseSharingViolation,	"JET_errDatabaseSharingViolation",	"A different database instance is using this database" },
	{ JET_errAttachedDatabaseMismatch,	"JET_errAttachedDatabaseMismatch",	"An outstanding database attachment has been detected at the start or end of recovery, but database is missing or does not match attachment info" },
	{ JET_errDatabaseInvalidPath,	"JET_errDatabaseInvalidPath",	"Specified path to database file is illegal" },
	{ JET_errDatabaseIdInUse,	"JET_errDatabaseIdInUse",	"A database is being assigned an id already in use" },
	{ JET_errForceDetachNotAllowed,	"JET_errForceDetachNotAllowed",	"Force Detach allowed only after normal detach errored out" },
	{ JET_errCatalogCorrupted,	"JET_errCatalogCorrupted",	"Corruption detected in catalog" },
	{ JET_errPartiallyAttachedDB,	"JET_errPartiallyAttachedDB",	"Database is partially attached. Cannot complete attach operation" },
	{ JET_errDatabaseSignInUse,	"JET_errDatabaseSignInUse",	"Database with same signature in use" },
	{ JET_wrnTableEmpty,	"JET_wrnTableEmpty",	"Opened an empty table" },
	{ JET_errTableLocked,	"JET_errTableLocked",	"Table is exclusively locked" },
	{ JET_errTableDuplicate,	"JET_errTableDuplicate",	"Table already exists" },
	{ JET_errTableInUse,	"JET_errTableInUse",	"Table is in use, cannot lock" },
	{ JET_errObjectNotFound,	"JET_errObjectNotFound",	"No such table or object" },
	{ JET_errDensityInvalid,	"JET_errDensityInvalid",	"Bad file/index density" },
	{ JET_errTableNotEmpty,	"JET_errTableNotEmpty",	"Table is not empty" },
	{ JET_errInvalidTableId,	"JET_errInvalidTableId",	"Invalid table id" },
	{ JET_errTooManyOpenTables,	"JET_errTooManyOpenTables",	"Cannot open any more tables (cleanup already attempted)" },
	{ JET_errIllegalOperation,	"JET_errIllegalOperation",	"Oper. not supported on table" },
	{ JET_errTooManyOpenTablesAndCleanupTimedOut,	"JET_errTooManyOpenTablesAndCleanupTimedOut",	"Cannot open any more tables (cleanup attempt failed to complete)" },
	{ JET_errObjectDuplicate,	"JET_errObjectDuplicate",	"Table or object name in use" },
	{ JET_errInvalidObject,	"JET_errInvalidObject",	"Object is invalid for operation" },
	{ JET_errCannotDeleteTempTable,	"JET_errCannotDeleteTempTable",	"Use CloseTable instead of DeleteTable to delete temp table" },
	{ JET_errCannotDeleteSystemTable,	"JET_errCannotDeleteSystemTable",	"Illegal attempt to delete a system table" },
	{ JET_errCannotDeleteTemplateTable,	"JET_errCannotDeleteTemplateTable",	"Illegal attempt to delete a template table" },
	{ JET_errExclusiveTableLockRequired,	"JET_errExclusiveTableLockRequired",	"Must have exclusive lock on table." },
	{ JET_errFixedDDL,	"JET_errFixedDDL",	"DDL operations prohibited on this table" },
	{ JET_errFixedInheritedDDL,	"JET_errFixedInheritedDDL",	"On a derived table, DDL operations are prohibited on inherited portion of DDL" },
	{ JET_errCannotNestDDL,	"JET_errCannotNestDDL",	"Nesting of hierarchical DDL is not currently supported." },
	{ JET_errDDLNotInheritable,	"JET_errDDLNotInheritable",	"Tried to inherit DDL from a table not marked as a template table." },
	{ JET_wrnTableInUseBySystem,	"JET_wrnTableInUseBySystem",	"System cleanup has a cursor open on the table" },
	{ JET_errInvalidSettings,	"JET_errInvalidSettings",	"System parameters were set improperly" },
	{ JET_errClientRequestToStopJetService,	"JET_errClientRequestToStopJetService",	"Client has requested stop service" },
	{ JET_errCannotAddFixedVarColumnToDerivedTable,	"JET_errCannotAddFixedVarColumnToDerivedTable",	"Template table was created with NoFixedVarColumnsInDerivedTables" },
	{ JET_errIndexCantBuild,	"JET_errIndexCantBuild",	"Index build failed" },
	{ JET_errIndexHasPrimary,	"JET_errIndexHasPrimary",	"Primary index already defined" },
	{ JET_errIndexDuplicate,	"JET_errIndexDuplicate",	"Index is already defined" },
	{ JET_errIndexNotFound,	"JET_errIndexNotFound",	"No such index" },
	{ JET_errIndexMustStay,	"JET_errIndexMustStay",	"Cannot delete clustered index" },
	{ JET_errIndexInvalidDef,	"JET_errIndexInvalidDef",	"Illegal index definition" },
	{ JET_errInvalidCreateIndex,	"JET_errInvalidCreateIndex",	"Invalid create index description" },
	{ JET_errTooManyOpenIndexes,	"JET_errTooManyOpenIndexes",	"Out of index description blocks" },
	{ JET_errMultiValuedIndexViolation,	"JET_errMultiValuedIndexViolation",	"Non-unique inter-record index keys generated for a multivalued index" },
	{ JET_errIndexBuildCorrupted,	"JET_errIndexBuildCorrupted",	"Failed to build a secondary index that properly reflects primary index" },
	{ JET_errPrimaryIndexCorrupted,	"JET_errPrimaryIndexCorrupted",	"Primary index is corrupt. The database must be defragmented" },
	{ JET_errSecondaryIndexCorrupted,	"JET_errSecondaryIndexCorrupted",	"Secondary index is corrupt. The database must be defragmented" },
	{ JET_wrnCorruptIndexDeleted,	"JET_wrnCorruptIndexDeleted",	"Out of date index removed" },
	{ JET_errInvalidIndexId,	"JET_errInvalidIndexId",	"Illegal index id" },
	{ JET_errIndexTuplesSecondaryIndexOnly,	"JET_errIndexTuplesSecondaryIndexOnly",	"tuple index can only be on a secondary index" },
	{ JET_errIndexTuplesOneColumnOnly,	"JET_errIndexTuplesOneColumnOnly",	"tuple index may only have one column in the index" },
	{ JET_errIndexTuplesNonUniqueOnly,	"JET_errIndexTuplesNonUniqueOnly",	"tuple index must be a non-unique index" },
	{ JET_errIndexTuplesTextColumnsOnly,	"JET_errIndexTuplesTextColumnsOnly",	"tuple index must be on a text column" },
	{ JET_errIndexTuplesVarSegMacNotAllowed,	"JET_errIndexTuplesVarSegMacNotAllowed",	"tuple index does not allow setting cbVarSegMac" },
	{ JET_errIndexTuplesInvalidLimits,	"JET_errIndexTuplesInvalidLimits",	"invalid min/max tuple length or max characters to index specified" },
	{ JET_errIndexTuplesCannotRetrieveFromIndex,	"JET_errIndexTuplesCannotRetrieveFromIndex",	"cannot call RetrieveColumn() with RetrieveFromIndex on a tuple index" },
	{ JET_errIndexTuplesKeyTooSmall,	"JET_errIndexTuplesKeyTooSmall",	"specified key does not meet minimum tuple length" },
	{ JET_errColumnLong,	"JET_errColumnLong",	"Column value is long" },
	{ JET_errColumnNoChunk,	"JET_errColumnNoChunk",	"No such chunk in long value" },
	{ JET_errColumnDoesNotFit,	"JET_errColumnDoesNotFit",	"Field will not fit in record" },
	{ JET_errNullInvalid,	"JET_errNullInvalid",	"Null not valid" },
	{ JET_errColumnIndexed,	"JET_errColumnIndexed",	"Column indexed, cannot delete" },
	{ JET_errColumnTooBig,	"JET_errColumnTooBig",	"Field length is greater than maximum" },
	{ JET_errColumnNotFound,	"JET_errColumnNotFound",	"No such column" },
	{ JET_errColumnDuplicate,	"JET_errColumnDuplicate",	"Field is already defined" },
	{ JET_errMultiValuedColumnMustBeTagged,	"JET_errMultiValuedColumnMustBeTagged",	"Attempted to create a multi-valued column, but column was not Tagged" },
	{ JET_errColumnRedundant,	"JET_errColumnRedundant",	"Second autoincrement or version column" },
	{ JET_errInvalidColumnType,	"JET_errInvalidColumnType",	"Invalid column data type" },
	{ JET_wrnColumnMaxTruncated,	"JET_wrnColumnMaxTruncated",	"Max length too big, truncated" },
	{ JET_errTaggedNotNULL,	"JET_errTaggedNotNULL",	"No non-NULL tagged columns" },
	{ JET_errNoCurrentIndex,	"JET_errNoCurrentIndex",	"Invalid w/o a current index" },
	{ JET_errKeyIsMade,	"JET_errKeyIsMade",	"The key is completely made" },
	{ JET_errBadColumnId,	"JET_errBadColumnId",	"Column Id Incorrect" },
	{ JET_errBadItagSequence,	"JET_errBadItagSequence",	"Bad itagSequence for tagged column" },
	{ JET_errColumnInRelationship,	"JET_errColumnInRelationship",	"Cannot delete, column participates in relationship" },
	{ JET_wrnCopyLongValue,	"JET_wrnCopyLongValue",	"Single instance column bursted" },
	{ JET_errCannotBeTagged,	"JET_errCannotBeTagged",	"AutoIncrement and Version cannot be tagged" },
	{ JET_wrnTaggedColumnsRemaining,	"JET_wrnTaggedColumnsRemaining",	"RetrieveTaggedColumnList ran out of copy buffer before retrieving all tagged columns" },
	{ JET_errDefaultValueTooBig,	"JET_errDefaultValueTooBig",	"Default value exceeds maximum size" },
	{ JET_errMultiValuedDuplicate,	"JET_errMultiValuedDuplicate",	"Duplicate detected on a unique multi-valued column" },
	{ JET_errLVCorrupted,	"JET_errLVCorrupted",	"Corruption encountered in long-value tree" },
	{ JET_errMultiValuedDuplicateAfterTruncation,	"JET_errMultiValuedDuplicateAfterTruncation",	"Duplicate detected on a unique multi-valued column after data was normalized, and normalizing truncated the data before comparison" },
	{ JET_errDerivedColumnCorruption,	"JET_errDerivedColumnCorruption",	"Invalid column in derived table" },
	{ JET_errInvalidPlaceholderColumn,	"JET_errInvalidPlaceholderColumn",	"Tried to convert column to a primary index placeholder, but column doesn't meet necessary criteria" },
	{ JET_wrnColumnSkipped,	"JET_wrnColumnSkipped",	"Column value(s) not returned because the corresponding column id or itagSequence requested for enumeration was null" },
	{ JET_wrnColumnNotLocal,	"JET_wrnColumnNotLocal",	"Column value(s) not returned because they could not be reconstructed from the data at hand" },
	{ JET_wrnColumnMoreTags,	"JET_wrnColumnMoreTags",	"Column values exist that were not requested for enumeration" },
	{ JET_wrnColumnTruncated,	"JET_wrnColumnTruncated",	"Column value truncated at the requested size limit during enumeration" },
	{ JET_wrnColumnPresent,	"JET_wrnColumnPresent",	"Column values exist but were not returned by request" },
	{ JET_wrnColumnSingleValue,	"JET_wrnColumnSingleValue",	"Column value returned in JET_COLUMNENUM as a result of JET_bitEnumerateCompressOutput" },
	{ JET_errRecordNotFound,	"JET_errRecordNotFound",	"The key was not found" },
	{ JET_errRecordNoCopy,	"JET_errRecordNoCopy",	"No working buffer" },
	{ JET_errNoCurrentRecord,	"JET_errNoCurrentRecord",	"Currency not on a record" },
	{ JET_errRecordPrimaryChanged,	"JET_errRecordPrimaryChanged",	"Primary key may not change" },
	{ JET_errKeyDuplicate,	"JET_errKeyDuplicate",	"Illegal duplicate key" },
	{ JET_errAlreadyPrepared,	"JET_errAlreadyPrepared",	"Attempted to update record when record update was already in progress" },
	{ JET_errKeyNotMade,	"JET_errKeyNotMade",	"No call to JetMakeKey" },
	{ JET_errUpdateNotPrepared,	"JET_errUpdateNotPrepared",	"No call to JetPrepareUpdate" },
	{ JET_wrnDataHasChanged,	"JET_wrnDataHasChanged",	"Data has changed" },
	{ JET_errDataHasChanged,	"JET_errDataHasChanged",	"Data has changed, operation aborted" },
	{ JET_wrnKeyChanged,	"JET_wrnKeyChanged",	"Moved to new key" },
	{ JET_errLanguageNotSupported,	"JET_errLanguageNotSupported",	"WindowsNT installation does not support language" },
	{ JET_errTooManySorts,	"JET_errTooManySorts",	"Too many sort processes" },
	{ JET_errInvalidOnSort,	"JET_errInvalidOnSort",	"Invalid operation on Sort" },
	{ JET_errTempFileOpenError,	"JET_errTempFileOpenError",	"Temp file could not be opened" },
	{ JET_errTooManyAttachedDatabases,	"JET_errTooManyAttachedDatabases",	"Too many open databases" },
	{ JET_errDiskFull,	"JET_errDiskFull",	"No space left on disk" },
	{ JET_errPermissionDenied,	"JET_errPermissionDenied",	"Permission denied" },
	{ JET_errFileNotFound,	"JET_errFileNotFound",	"File not found" },
	{ JET_errFileInvalidType,	"JET_errFileInvalidType",	"Invalid file type" },
	{ JET_wrnFileOpenReadOnly,	"JET_wrnFileOpenReadOnly",	"Database file is read only" },
	{ JET_errAfterInitialization,	"JET_errAfterInitialization",	"Cannot Restore after init." },
	{ JET_errLogCorrupted,	"JET_errLogCorrupted",	"Logs could not be interpreted" },
	{ JET_errInvalidOperation,	"JET_errInvalidOperation",	"Invalid operation" },
	{ JET_errAccessDenied,	"JET_errAccessDenied",	"Access denied" },
	{ JET_wrnIdleFull,	"JET_wrnIdleFull",	"Idle registry full" },
	{ JET_errTooManySplits,	"JET_errTooManySplits",	"Infinite split" },
	{ JET_errSessionSharingViolation,	"JET_errSessionSharingViolation",	"Multiple threads are using the same session" },
	{ JET_errEntryPointNotFound,	"JET_errEntryPointNotFound",	"An entry point in a DLL we require could not be found" },
	{ JET_errSessionContextAlreadySet,	"JET_errSessionContextAlreadySet",	"Specified session already has a session context set" },
	{ JET_errSessionContextNotSetByThisThread,	"JET_errSessionContextNotSetByThisThread",	"Tried to reset session context, but current thread did not orignally set the session context" },
	{ JET_errSessionInUse,	"JET_errSessionInUse",	"Tried to terminate session in use" },
	{ JET_errRecordFormatConversionFailed,	"JET_errRecordFormatConversionFailed",	"Internal error during dynamic record format conversion" },
	{ JET_errOneDatabasePerSession,	"JET_errOneDatabasePerSession",	"Just one open user database per session is allowed (JET_paramOneDatabasePerSession)" },
	{ JET_errRollbackError,	"JET_errRollbackError",	"error during rollback" },
	{ JET_wrnDefragAlreadyRunning,	"JET_wrnDefragAlreadyRunning",	"Online defrag already running on specified database" },
	{ JET_wrnDefragNotRunning,	"JET_wrnDefragNotRunning",	"Online defrag not running on specified database" },
	{ JET_wrnCallbackNotRegistered,	"JET_wrnCallbackNotRegistered",	"Unregistered a non-existant callback function" },
	{ JET_errCallbackFailed,	"JET_errCallbackFailed",	"A callback failed" },
	{ JET_errCallbackNotResolved,	"JET_errCallbackNotResolved",	"A callback function could not be found" },
	{ JET_errSLVSpaceCorrupted,	"JET_errSLVSpaceCorrupted",	"Corruption encountered in space manager of streaming file" },
	{ JET_errSLVCorrupted,	"JET_errSLVCorrupted",	"Corruption encountered in streaming file" },
	{ JET_errSLVColumnDefaultValueNotAllowed,	"JET_errSLVColumnDefaultValueNotAllowed",	"SLV columns cannot have a default value" },
	{ JET_errSLVStreamingFileMissing,	"JET_errSLVStreamingFileMissing",	"Cannot find streaming file associated with this database" },
	{ JET_errSLVDatabaseMissing,	"JET_errSLVDatabaseMissing",	"Streaming file exists, but database to which it belongs is missing" },
	{ JET_errSLVStreamingFileAlreadyExists,	"JET_errSLVStreamingFileAlreadyExists",	"Tried to create a streaming file when one already exists or is already recorded in the catalog" },
	{ JET_errSLVInvalidPath,	"JET_errSLVInvalidPath",	"Specified path to a streaming file is invalid" },
	{ JET_errSLVStreamingFileNotCreated,	"JET_errSLVStreamingFileNotCreated",	"Tried to perform an SLV operation but streaming file was never created" },
	{ JET_errSLVStreamingFileReadOnly,	"JET_errSLVStreamingFileReadOnly",	"Attach a readonly streaming file for read/write operations" },
	{ JET_errSLVHeaderBadChecksum,	"JET_errSLVHeaderBadChecksum",	"SLV file header failed checksum verification" },
	{ JET_errSLVHeaderCorrupted,	"JET_errSLVHeaderCorrupted",	"SLV file header contains invalid information" },
	{ JET_errSLVPagesNotFree,	"JET_errSLVPagesNotFree",	"Tried to move pages from the Free state when they were not in that state" },
	{ JET_errSLVPagesNotReserved,	"JET_errSLVPagesNotReserved",	"Tried to move pages from the Reserved state when they were not in that state" },
	{ JET_errSLVPagesNotCommitted,	"JET_errSLVPagesNotCommitted",	"Tried to move pages from the Committed state when they were not in that state" },
	{ JET_errSLVPagesNotDeleted,	"JET_errSLVPagesNotDeleted",	"Tried to move pages from the Deleted state when they were not in that state" },
	{ JET_errSLVSpaceWriteConflict,	"JET_errSLVSpaceWriteConflict",	"Unexpected conflict detected trying to write-latch SLV space pages" },
	{ JET_errSLVRootStillOpen,	"JET_errSLVRootStillOpen",	"The database can not be created/attached because its corresponding SLV Root is still open by another process." },
	{ JET_errSLVProviderNotLoaded,	"JET_errSLVProviderNotLoaded",	"The database can not be created/attached because the SLV Provider has not been loaded." },
	{ JET_errSLVEAListCorrupt,	"JET_errSLVEAListCorrupt",	"The specified SLV EA List is corrupted." },
	{ JET_errSLVRootNotSpecified,	"JET_errSLVRootNotSpecified",	"The database cannot be created/attached because the SLV Root Name was omitted" },
	{ JET_errSLVRootPathInvalid,	"JET_errSLVRootPathInvalid",	"The specified SLV Root path was invalid." },
	{ JET_errSLVEAListZeroAllocation,	"JET_errSLVEAListZeroAllocation",	"The specified SLV EA List has no allocated space." },
	{ JET_errSLVColumnCannotDelete,	"JET_errSLVColumnCannotDelete",	"Deletion of SLV columns is not currently supported." },
	{ JET_errSLVOwnerMapAlreadyExists,	"JET_errSLVOwnerMapAlreadyExists",	"Tried to create a new catalog entry for SLV Ownership Map when one already exists" },
	{ JET_errSLVSpaceMapAlreadyExists,	"JET_errSLVSpaceMapAlreadyExists",	"OBSOLETE: Renamed to JET_errSLVOwnerMapCorrupted" },
	{ JET_errSLVOwnerMapCorrupted,	"JET_errSLVOwnerMapCorrupted",	"Corruption encountered in SLV Ownership Map" },
	{ JET_errSLVSpaceMapCorrupted,	"JET_errSLVSpaceMapCorrupted",	"OBSOLETE: Renamed to JET_errSLVOwnerMapCorrupted" },
	{ JET_errSLVOwnerMapPageNotFound,	"JET_errSLVOwnerMapPageNotFound",	"Corruption encountered in SLV Ownership Map" },
	{ JET_errSLVSpaceMapPageNotFound,	"JET_errSLVSpaceMapPageNotFound",	"OBSOLETE: Renamed to JET_errSLVOwnerMapPageNotFound" },
	{ JET_errSLVFileStale,	"JET_errSLVFileStale",	"The specified SLV File handle belongs to a SLV Root that no longer exists." },
	{ JET_errSLVFileInUse,	"JET_errSLVFileInUse",	"The specified SLV File is currently in use" },
	{ JET_errSLVStreamingFileInUse,	"JET_errSLVStreamingFileInUse",	"The specified streaming file is currently in use" },
	{ JET_errSLVFileIO,	"JET_errSLVFileIO",	"An I/O error occurred while accessing an SLV File (general read / write failure)" },
	{ JET_errSLVStreamingFileFull,	"JET_errSLVStreamingFileFull",	"No space left in the streaming file" },
	{ JET_errSLVFileInvalidPath,	"JET_errSLVFileInvalidPath",	"Specified path to a SLV File was invalid" },
	{ JET_errSLVFileAccessDenied,	"JET_errSLVFileAccessDenied",	"Cannot access SLV File, the SLV File is locked or is in use" },
	{ JET_errSLVFileNotFound,	"JET_errSLVFileNotFound",	"The specified SLV File was not found" },
	{ JET_errSLVFileUnknown,	"JET_errSLVFileUnknown",	"An unknown error occurred while accessing an SLV File" },
	{ JET_errSLVEAListTooBig,	"JET_errSLVEAListTooBig",	"The specified SLV EA List could not be returned because it is too large to fit in the standard EA format.  Retrieve the SLV File as a file handle instead." },
	{ JET_errSLVProviderVersionMismatch,	"JET_errSLVProviderVersionMismatch",	"The loaded SLV Provider's version does not match the database engine's version." },
	{ JET_errSLVBufferTooSmall,	"JET_errSLVBufferTooSmall",	"Buffer allocated for SLV data or meta-data was too small" },
	{ JET_errOSSnapshotInvalidSequence,	"JET_errOSSnapshotInvalidSequence",	"OS Shadow copy API used in an invalid sequence" },
	{ JET_errOSSnapshotTimeOut,	"JET_errOSSnapshotTimeOut",	"OS Shadow copy ended with time-out" },
	{ JET_errOSSnapshotNotAllowed,	"JET_errOSSnapshotNotAllowed",	"OS Shadow copy not allowed (backup or recovery in progress)" },
	{ JET_errLSCallbackNotSpecified,	"JET_errLSCallbackNotSpecified",	"Attempted to use Local Storage without a callback function being specified" },
	{ JET_errLSAlreadySet,	"JET_errLSAlreadySet",	"Attempted to set Local Storage for an object which already had it set" },
	{ JET_errLSNotSet,	"JET_errLSNotSet",	"Attempted to retrieve Local Storage from an object which didn't have it set" },
	{ JET_errFileIOBeyondEOF,	"JET_errFileIOBeyondEOF",	"a read was issued to a location beyond EOF (writes will expand the file)" },
	{ JET_errFileIOAbort,	"JET_errFileIOAbort",	"instructs the JET_ABORTRETRYFAILCALLBACK caller to abort the specified I/O" },
	{ JET_errFileIORetry,	"JET_errFileIORetry",	"instructs the JET_ABORTRETRYFAILCALLBACK caller to retry the specified I/O" },
	{ JET_errFileIOFail,	"JET_errFileIOFail",	"instructs the JET_ABORTRETRYFAILCALLBACK caller to fail the specified I/O" },
	{ JET_errFileCompressed,	"JET_errFileCompressed",	"read/write access is not supported on compressed files" },
};

JET_ERR ErrStringToJetError( const char * szError, JET_ERR * perr )
	{
	const ERROR * const perror = find_if( rgerror, rgerror + ( sizeof( rgerror ) / sizeof( ERROR ) ), FIND_ERRSTR( szError ) );
	if( ( rgerror + ( sizeof( rgerror ) / sizeof( ERROR ) ) ) != perror )
		{
		*perr = perror->err;
		return JET_errSuccess;
		}
	else
		{
		return JET_errInvalidParameter;
		}
	}
	
void JetErrorToString( JET_ERR err, const char **szError, const char **szErrorText )
	{
	const ERROR * const perror = find_if( rgerror, rgerror + ( sizeof( rgerror ) / sizeof( ERROR ) ), FIND_ERRNUM( err ) );
	if( ( rgerror + ( sizeof( rgerror ) / sizeof( ERROR ) ) ) != perror )
		{
		*szError = perror->szError;
		*szErrorText = perror->szErrorText;
		}
	else
		{
		*szError = szUnknownError;
		*szErrorText = szUnknownError;
		}
	}

#endif // MINIMAL_FUNCTIONALITY

