;--------------------------------------------
; file: luna\themes.ini
;--------------------------------------------

[documentation]
DisplayName = OpenNT Style
LastUpdated = 11/13/2021
ToolTip = OpenNT Visual Style
Author = Dayum2002
Version = .01
Description = Windows Vista aero style for OpenNT
ThemeName = Royale
WmpSkinName = Default       ; change this to a real WMP skin name

;---------- Color Schemes for this theme ------------
[ColorScheme.NormalColor]
DisplayName = Default
ToolTip = default blue color scheme

;---------- Sizes for this theme ------------
[Size.NormalSize]
DisplayName = Normal
ToolTip = Normal size

;---------- Substitution tables for this theme ------------
[Subst.Common]

[Subst.NormalColor]
Include = Common

[Subst.NormalSize]
SBWidth = 17
SBHeight = 17
CaptionBarHeight = 20
CaptionBarWidth = 20
SMCaptionBarHeight = 17
SMCaptionBarWidth = 20
CaptionFont = Segoe UI, 9
SmallCaptionFont = Segoe UI, 9
MenuFont = Segoe UI, 9
StatusFont = Segoe UI, 9
MsgBoxFont = Segoe UI, 8
IconTitleFont = Segoe UI, 9
Tahoma8 = Segoe UI, 9
Tahoma8Bold = Segoe UI, 9, Bold
StartPanelFont = Segoe UI, 16, Bold
StartButtonFont = Segoe UI, 14


;---------- ClassData files for this theme ------------
[File.NormalAero]
FileName = Aero\Aero.ini
ColorSchemes = NormalColor
Sizes = NormalSize

