386_OBJECTS=

PASS0_386_OBJECTS= \
    $(PASS0_HEADERDIR)\cievtmsg.h \
    $(MC_SOURCEDIR)\cievtmsg.rc

IA64_OBJECTS=

PASS0_IA64_OBJECTS= \
    $(PASS0_HEADERDIR)\cievtmsg.h \
    $(MC_SOURCEDIR)\cievtmsg.rc

AMD64_OBJECTS=

PASS0_AMD64_OBJECTS= \
    $(PASS0_HEADERDIR)\cievtmsg.h \
    $(MC_SOURCEDIR)\cievtmsg.rc

ARM_OBJECTS=

PASS0_ARM_OBJECTS= \
    $(PASS0_HEADERDIR)\cievtmsg.h \
    $(MC_SOURCEDIR)\cievtmsg.rc

