386_OBJECTS= \
    $(_OBJ_DIR)\i386\certreqd.res \
    $(_OBJ_DIR)\i386\certreqd.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\certreqd.res \
    $(_OBJ_DIR)\ia64\certreqd.obj

PASS0_IA64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\certreqd.res \
    $(_OBJ_DIR)\amd64\certreqd.obj

PASS0_AMD64_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\certreqd.res \
    $(_OBJ_DIR)\arm\certreqd.obj

PASS0_ARM_OBJECTS=

